source("R/utils_card_images.R")

local({
  root <- tempfile("card-images-")
  on.exit(unlink(root, recursive = TRUE), add = TRUE)
  cards <- file.path(root, "cards")
  illustrations <- file.path(root, "illustrations")
  dir.create(cards, recursive = TRUE)
  dir.create(illustrations)
  old <- file.path(cards, "example.jpg")
  new <- file.path(illustrations, "example.webp")
  stopifnot(is.na(card_image_path("example", cards, illustrations)))
  file.create(old)
  stopifnot(identical(card_image_path("example", cards, illustrations), old))
  file.create(new)
  stopifnot(identical(card_image_path("example", cards, illustrations), new))
  validate_card_images(data.frame(id = "example"), cards, illustrations)
})
cat("Sélection des illustrations et repli sur les anciennes images : OK.\n")
