<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Arbres publics sur le territoire de Montréal – Données bleues</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-678eb615bd8f57929f3ad5b5079cb7e5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Arbres publics sur le territoire de Montréal – Données bleues">
<meta property="og:site_name" content="Données bleues">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/logo-donnees-bleues.svg" alt="Logo Données bleues" class="navbar-logo light-content">
    <img src="../../assets/logo-donnees-bleues.svg" alt="Logo Données bleues" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Données bleues</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Recherche"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Basculer la navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Accueil</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../catalogue.html"> 
<span class="menu-text">Explorer</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../activites.html"> 
<span class="menu-text">Planifier</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../sequences.html"> 
<span class="menu-text">Séquences</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../zero-waste.html"> 
<span class="menu-text">Méthode</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">À propos</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../references.html"> <i class="bi bi-book" role="img">
</i> 
<span class="menu-text">Documentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/AurelienNicosiaULaval/donnees-bleues"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">GitHub</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../contribuer.html"> 
<span class="menu-text">Contribuer</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content page-columns page-full column-page" id="quarto-document-content">



<section class="dataset-detail-page page-columns page-full">
<section class="dataset-teacher-hero page-columns page-full">
<div class="dataset-hero-copy">
<nav class="dataset-breadcrumb">
<a href="../../catalogue.html">Catalogue</a><span>/</span><span>Foresterie urbaine</span>
</nav>
<h1>
Arbres publics sur le territoire de Montréal
</h1>
<p class="dataset-teacher-question">
Quelles essences d'arbres publics sont les plus fréquentes dans un arrondissement choisi?
</p>
<div class="dataset-source-strip">
<span>Source : <a href="https://www.donneesquebec.ca/recherche/dataset/vmtl-arbres">Données Québec / Ville de Montréal</a></span><span>Licence : Attribution (CC-BY 4.0) selon les métadonnées CKAN vérifiées le 2026-06-21</span><span>Téléchargé : 2026-06-21</span>
</div>
<div class="dataset-hero-actions">
<a class="dataset-button no-external" href="#apercu-interactif">Voir les données</a><a class="dataset-button secondary no-external" href="#activites-pedagogiques">Activités</a>
</div>
</div>
<aside class="dataset-featured-activity">
<span class="dataset-panel-label">Activité prête à lancer</span>
<h2 class="anchored">
Essences d'arbres par arrondissement
</h2>
<p>
Quelles essences d'arbres publics sont les plus fréquentes dans un arrondissement choisi?
</p>
<div class="dataset-featured-meta">
<span>30-45 minutes</span><span>Introductif</span><span>Prête à enseigner</span>
</div>
<div class="dataset-activity-chips">
<span class="dataset-activity-chip">Laboratoire</span><span class="dataset-activity-chip">Exploration de données</span>
</div>
</aside>
</section>
<section class="dataset-teacher-plan">
<article>
<span class="dataset-panel-label">Pourquoi l’utiliser?</span>
<p>
Pour travailler Comptage, Catégories, Visualisation, Qualité des données à partir d’un contexte foresterie urbaine lié à Montréal.
</p>
<div class="dataset-chip-row">
<span class="dataset-chip">Comptage</span><span class="dataset-chip">Catégories</span><span class="dataset-chip">Visualisation</span><span class="dataset-chip">Qualité des données</span><span class="dataset-chip">environnement urbain</span><span class="dataset-chip">arbres</span>
</div>
</article>
<article>
<span class="dataset-panel-label">Ce que les étudiantes et étudiants font</span>
<ul>
<li>
Comparer les essences d'arbres publics par arrondissement.
</li>
<li>
Cartographier un extrait ou une agrégation des arbres publics tout en discutant la qualité des coordonnées.
</li>
<li>
Analyser les valeurs manquantes et les dates non plausibles avant toute interprétation écologique.
</li>
</ul>
</article>
<article>
<span class="dataset-panel-label">À cadrer en classe</span>
<p>
Préparer un extrait si la taille du fichier ralentit les postes étudiants.
</p>
</article>
</section>
<section class="dataset-r-lab" id="apercu-interactif">
<div class="dataset-section-heading">
<span>Aperçu des données</span>
<h2 class="anchored">
Entrer par les lignes, puis poser une question
</h2>
<p>
Extrait public de la table préparée à partir de la source officielle, limité à 120 lignes pour une exploration rapide.
</p>
</div>
<div class="dataset-preview-layout">
<div class="dataset-result-card">
<div class="dataset-card-label">
Table consultable
</div>
<div id="dataset-header-result-table" class="dataset-datatable">
<div class="dataset-datatable-toolbar">
<label><span>Recherche</span><input type="search" data-dataset-search="" placeholder="Filtrer"></label><label><span>Lignes</span><select data-dataset-page-size=""><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select></label><span class="dataset-datatable-count" data-dataset-count=""></span>
</div>
<div class="dataset-result-table-wrap">
<table class="dataset-result-table">
<thead>
<tr>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="0">
inventaire_type<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="1">
arbre_id<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="2">
arrondissement_code<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="3">
arrondissement<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="4">
emplacement<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="5">
sigle<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="6">
essence_latin<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="7">
essence_fr<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="8">
essence_ang<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="9">
dhp<span aria-hidden="true"></span>
</button>
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
H
</td>
<td>
106127
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
ABSI
</td>
<td>
Abies sibirica
</td>
<td>
Abies sibirica
</td>
<td>
Abies sibirica
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
133268
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
GYDI
</td>
<td>
Gymnocladus dioicus
</td>
<td>
Chicot du Canada
</td>
<td>
Kentucky Coffeetree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
102924
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
FRPE
</td>
<td>
Fraxinus pennsylvanica
</td>
<td>
Frêne de Pennsylvanie
</td>
<td>
Red Ash
</td>
<td>
35
</td>
</tr>
<tr>
<td>
R
</td>
<td>
134020
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
GLTRSK
</td>
<td>
Gleditsia triacanthos 'Skyline'
</td>
<td>
Févier Skyline
</td>
<td>
Skyline Honey-Locust
</td>
<td>
21
</td>
</tr>
<tr>
<td>
R
</td>
<td>
253464
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
GIBI
</td>
<td>
Ginkgo biloba
</td>
<td>
Ginkgo à feuilles bilobées
</td>
<td>
Maidenhair Tree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
192589
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Terre-plein Gazonné
</td>
<td>
CEOC
</td>
<td>
Celtis occidentalis
</td>
<td>
Micocoulier occidental
</td>
<td>
Common Hackberry
</td>
<td>
25
</td>
</tr>
<tr>
<td>
R
</td>
<td>
123434
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
TRottoir
</td>
<td>
ULPU
</td>
<td>
Ulmus pumila
</td>
<td>
Orme de Sibérie
</td>
<td>
Siberian Elm
</td>
<td>
68
</td>
</tr>
<tr>
<td>
R
</td>
<td>
116613
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
PLACEX
</td>
<td>
Platanus x a. 'Morton Circle (Exclamation TM)
</td>
<td>
Platane Exclamation
</td>
<td>
Exclamation London Planetree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
105100
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
TICO
</td>
<td>
Tilia cordata
</td>
<td>
Tilleul à petites feuilles
</td>
<td>
Littleleaf European Linden
</td>
<td>
43
</td>
</tr>
<tr>
<td>
R
</td>
<td>
120994
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
ULXXPA
</td>
<td>
Ulmus x 'Patriots'
</td>
<td>
Ulmus x Patriots
</td>
<td>
Ulmus x Patriots
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
106306
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Banquette Gazonnée
</td>
<td>
ACSA
</td>
<td>
Acer saccharinum
</td>
<td>
Érable argenté
</td>
<td>
Silver Maple
</td>
<td>
36
</td>
</tr>
<tr>
<td>
H
</td>
<td>
19050
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
ACSA
</td>
<td>
Acer saccharinum
</td>
<td>
Érable argenté
</td>
<td>
Silver Maple
</td>
<td>
63
</td>
</tr>
<tr>
<td>
R
</td>
<td>
108604
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
ACPLDE
</td>
<td>
Acer platanoides 'Deborah'
</td>
<td>
Érable de Norvège Deborah
</td>
<td>
Deborah Norway Maple
</td>
<td>
26
</td>
</tr>
<tr>
<td>
H
</td>
<td>
86197
</td>
<td>
1
</td>
<td>
Ahuntsic - Cartierville
</td>
<td>
Parterre Gazonné
</td>
<td>
ACSCTU
</td>
<td>
Acer saccharum 'Temple Upright'
</td>
<td>
Érable à sucre Temple Upright
</td>
<td>
Temple Upright Sugar Maple
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
755929
</td>
<td>
7
</td>
<td>
Côte-des-Neiges - Notre-Dame-de-Grâce
</td>
<td>
Parterre Gazonné
</td>
<td>
GYDI
</td>
<td>
Gymnocladus dioicus
</td>
<td>
Chicot du Canada
</td>
<td>
Kentucky Coffeetree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
465505
</td>
<td>
7
</td>
<td>
Côte-des-Neiges - Notre-Dame-de-Grâce
</td>
<td>
Parterre Gazonné
</td>
<td>
GLTRSH
</td>
<td>
Gleditsia triacanthos 'Shademaster'
</td>
<td>
Févier Shademaster
</td>
<td>
Shademaster Honey-Locust
</td>
<td>
9
</td>
</tr>
<tr>
<td>
R
</td>
<td>
168416
</td>
<td>
7
</td>
<td>
Côte-des-Neiges - Notre-Dame-de-Grâce
</td>
<td>
Parterre Gazonné
</td>
<td>
SYREIS
</td>
<td>
Syringa reticulata 'Ivory Silk'
</td>
<td>
Lilas japonais Ivory Silk
</td>
<td>
Ivory Silk Japanese Tree Lilac
</td>
<td>
31
</td>
</tr>
<tr>
<td>
R
</td>
<td>
302925
</td>
<td>
7
</td>
<td>
Côte-des-Neiges - Notre-Dame-de-Grâce
</td>
<td>
Parterre Gazonné
</td>
<td>
ULHOPI
</td>
<td>
Ulmus x hollandica 'Pioneer'
</td>
<td>
Orme Pioneer
</td>
<td>
Pioneer Elm
</td>
<td>
9
</td>
</tr>
<tr>
<td>
R
</td>
<td>
73866
</td>
<td>
7
</td>
<td>
Côte-des-Neiges - Notre-Dame-de-Grâce
</td>
<td>
PaRterre
</td>
<td>
MA
</td>
<td>
Malus
</td>
<td>
Pommier
</td>
<td>
Crab Apple
</td>
<td>
19
</td>
</tr>
<tr>
<td>
R
</td>
<td>
81714
</td>
<td>
7
</td>
<td>
Côte-des-Neiges - Notre-Dame-de-Grâce
</td>
<td>
PaRterre
</td>
<td>
TICO
</td>
<td>
Tilia cordata
</td>
<td>
Tilleul à petites feuilles
</td>
<td>
Littleleaf European Linden
</td>
<td>
45
</td>
</tr>
<tr>
<td>
H
</td>
<td>
29890
</td>
<td>
7
</td>
<td>
Côte-des-Neiges - Notre-Dame-de-Grâce
</td>
<td>
PArc
</td>
<td>
ACSA
</td>
<td>
Acer saccharinum
</td>
<td>
Érable argenté
</td>
<td>
Silver Maple
</td>
<td>
83.2
</td>
</tr>
<tr>
<td>
R
</td>
<td>
80457
</td>
<td>
7
</td>
<td>
Côte-des-Neiges - Notre-Dame-de-Grâce
</td>
<td>
PaRterre
</td>
<td>
ACSA
</td>
<td>
Acer saccharinum
</td>
<td>
Érable argenté
</td>
<td>
Silver Maple
</td>
<td>
63
</td>
</tr>
<tr>
<td>
R
</td>
<td>
65719
</td>
<td>
7
</td>
<td>
Côte-des-Neiges - Notre-Dame-de-Grâce
</td>
<td>
Parterre Gazonné
</td>
<td>
ACPL
</td>
<td>
Acer platanoides
</td>
<td>
Érable de Norvège
</td>
<td>
Norway Maple
</td>
<td>
78
</td>
</tr>
<tr>
<td>
R
</td>
<td>
74663
</td>
<td>
7
</td>
<td>
Côte-des-Neiges - Notre-Dame-de-Grâce
</td>
<td>
PaRterre
</td>
<td>
ACTA
</td>
<td>
Acer tataricum
</td>
<td>
Érable de Tartarie
</td>
<td>
Tartarian Maple
</td>
<td>
28
</td>
</tr>
<tr>
<td>
R
</td>
<td>
218336
</td>
<td>
24
</td>
<td>
Lachine
</td>
<td>
Parterre Gazonné
</td>
<td>
GLTRSU
</td>
<td>
Gleditsia triacanthos 'Sunburst'
</td>
<td>
Févier Sunburst
</td>
<td>
Sunburst Honey-Locust
</td>
<td>
11
</td>
</tr>
<tr>
<td>
R
</td>
<td>
220177
</td>
<td>
24
</td>
<td>
Lachine
</td>
<td>
Parterre Gazonné
</td>
<td>
TIAM
</td>
<td>
Tilia americana
</td>
<td>
Tilleul d'Amérique
</td>
<td>
Basswood
</td>
<td>
52
</td>
</tr>
<tr>
<td>
R
</td>
<td>
219115
</td>
<td>
24
</td>
<td>
Lachine
</td>
<td>
Parterre Gazonné
</td>
<td>
ACPL
</td>
<td>
Acer platanoides
</td>
<td>
Érable de Norvège
</td>
<td>
Norway Maple
</td>
<td>
28
</td>
</tr>
<tr>
<td>
R
</td>
<td>
376465
</td>
<td>
5
</td>
<td>
Le Plateau-Mont-Royal
</td>
<td>
Saillie Aménagée
</td>
<td>
GYDI
</td>
<td>
Gymnocladus dioicus
</td>
<td>
Chicot du Canada
</td>
<td>
Kentucky Coffeetree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
138744
</td>
<td>
5
</td>
<td>
Le Plateau-Mont-Royal
</td>
<td>
TRottoir
</td>
<td>
GLTRSH
</td>
<td>
Gleditsia triacanthos 'Shademaster'
</td>
<td>
Févier Shademaster
</td>
<td>
Shademaster Honey-Locust
</td>
<td>
16
</td>
</tr>
<tr>
<td>
R
</td>
<td>
163082
</td>
<td>
5
</td>
<td>
Le Plateau-Mont-Royal
</td>
<td>
Parterre Gazonné
</td>
<td>
AEGL
</td>
<td>
Aesculus glabra
</td>
<td>
Marronnier glabre
</td>
<td>
Ohio Buckeye
</td>
<td>
22
</td>
</tr>
<tr>
<td>
H
</td>
<td>
163222
</td>
<td>
5
</td>
<td>
Le Plateau-Mont-Royal
</td>
<td>
Parterre Gazonné
</td>
<td>
OSVI
</td>
<td>
Ostrya virginiana
</td>
<td>
Ostryer de Virginie
</td>
<td>
American Hop-Hornbeam Ironwood
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
5999
</td>
<td>
5
</td>
<td>
Le Plateau-Mont-Royal
</td>
<td>
TRottoir
</td>
<td>
ACFRAB
</td>
<td>
Acer x freemanii 'Autumn Blaze'
</td>
<td>
Érable Autumn Blaze
</td>
<td>
Autumn Blaze Freeman Maple
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
9093
</td>
<td>
5
</td>
<td>
Le Plateau-Mont-Royal
</td>
<td>
PArc
</td>
<td>
ACSA
</td>
<td>
Acer saccharinum
</td>
<td>
Érable argenté
</td>
<td>
Silver Maple
</td>
<td>
42
</td>
</tr>
<tr>
<td>
R
</td>
<td>
2007
</td>
<td>
5
</td>
<td>
Le Plateau-Mont-Royal
</td>
<td>
Banquette aSphaltée
</td>
<td>
ACPLSU
</td>
<td>
Acer platanoides 'Summershade'
</td>
<td>
Érable de Norvège Summershade
</td>
<td>
Summershade Norway Maple
</td>
<td>
28
</td>
</tr>
<tr>
<td>
R
</td>
<td>
376205
</td>
<td>
8
</td>
<td>
Le Sud-Ouest
</td>
<td>
Parterre Gazonné
</td>
<td>
GYDI
</td>
<td>
Gymnocladus dioicus
</td>
<td>
Chicot du Canada
</td>
<td>
Kentucky Coffeetree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
65837
</td>
<td>
8
</td>
<td>
Le Sud-Ouest
</td>
<td>
Banquette Gazonnée
</td>
<td>
FRPE
</td>
<td>
Fraxinus pennsylvanica
</td>
<td>
Frêne de Pennsylvanie
</td>
<td>
Red Ash
</td>
<td>
52
</td>
</tr>
<tr>
<td>
R
</td>
<td>
63796
</td>
<td>
8
</td>
<td>
Le Sud-Ouest
</td>
<td>
TRottoir
</td>
<td>
GLTRSK
</td>
<td>
Gleditsia triacanthos 'Skyline'
</td>
<td>
Févier Skyline
</td>
<td>
Skyline Honey-Locust
</td>
<td>
8
</td>
</tr>
<tr>
<td>
H
</td>
<td>
4308
</td>
<td>
8
</td>
<td>
Le Sud-Ouest
</td>
<td>
Parterre Gazonné
</td>
<td>
CEOC
</td>
<td>
Celtis occidentalis
</td>
<td>
Micocoulier occidental
</td>
<td>
Common Hackberry
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
10537
</td>
<td>
8
</td>
<td>
Le Sud-Ouest
</td>
<td>
Parterre Gazonné
</td>
<td>
PODE
</td>
<td>
Populus deltoides
</td>
<td>
Peuplier deltoïde
</td>
<td>
Eastern Cottonwood
</td>
<td>
50
</td>
</tr>
<tr>
<td>
H
</td>
<td>
3704
</td>
<td>
8
</td>
<td>
Le Sud-Ouest
</td>
<td>
Parterre Gazonné
</td>
<td>
TICO
</td>
<td>
Tilia cordata
</td>
<td>
Tilleul à petites feuilles
</td>
<td>
Littleleaf European Linden
</td>
<td>
31
</td>
</tr>
<tr>
<td>
H
</td>
<td>
4551
</td>
<td>
8
</td>
<td>
Le Sud-Ouest
</td>
<td>
Parterre Gazonné
</td>
<td>
ACSA
</td>
<td>
Acer saccharinum
</td>
<td>
Érable argenté
</td>
<td>
Silver Maple
</td>
<td>
29
</td>
</tr>
<tr>
<td>
R
</td>
<td>
67382
</td>
<td>
8
</td>
<td>
Le Sud-Ouest
</td>
<td>
TRottoir
</td>
<td>
ACPLSC
</td>
<td>
Acer platanoides 'Schwedleri'
</td>
<td>
Érable de Norvège Schwedleri
</td>
<td>
Schwedleri Norway Maple
</td>
<td>
46
</td>
</tr>
<tr>
<td>
R
</td>
<td>
644085
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
Saillie Drainante
</td>
<td>
ALGL
</td>
<td>
Alnus glutinosa
</td>
<td>
Aulne glutineux
</td>
<td>
European Black Alder
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
267554
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
Saillie Aménagée
</td>
<td>
GYDI
</td>
<td>
Gymnocladus dioicus
</td>
<td>
Chicot du Canada
</td>
<td>
Kentucky Coffeetree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
49200
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
Parterre Gazonné
</td>
<td>
FRAM
</td>
<td>
Fraxinus americana
</td>
<td>
Frêne d'Amérique
</td>
<td>
White Ash
</td>
<td>
34
</td>
</tr>
<tr>
<td>
R
</td>
<td>
10073
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
PaRterre
</td>
<td>
FRPEMS
</td>
<td>
Fraxinus pennsylvanica 'Marshall Seedless'
</td>
<td>
Frêne de Pennsylvanie Marshall Seedless
</td>
<td>
Marshall Seedless Red Ash
</td>
<td>
15
</td>
</tr>
<tr>
<td>
R
</td>
<td>
12941
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
Parterre Gazonné
</td>
<td>
GLTRIN
</td>
<td>
Gleditsia triacanthos var. inermis
</td>
<td>
Févier inerme d'Amérique
</td>
<td>
Thornless Honey-Locust
</td>
<td>
63
</td>
</tr>
<tr>
<td>
H
</td>
<td>
143455
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
PArc
</td>
<td>
FASYPU
</td>
<td>
Fagus sylvatica 'Purpurea'
</td>
<td>
Hêtre européen purpurea
</td>
<td>
Purpurea European Beech
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
153788
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
PArc
</td>
<td>
JUNI
</td>
<td>
Juglans nigra
</td>
<td>
Noyer noir
</td>
<td>
Eastern Black Walnut
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
188973
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
Parterre Gazonné
</td>
<td>
PHAMMA
</td>
<td>
Phellodendron amurensis 'Macho'
</td>
<td>
Phellodendron de l'Amour Macho
</td>
<td>
Macho Amur Cork Tree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
38624
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
Parterre Gazonné
</td>
<td>
THOC
</td>
<td>
Thuja occidentalis
</td>
<td>
Thuya occidental
</td>
<td>
Eastern White Cedar
</td>
<td>
12
</td>
</tr>
<tr>
<td>
R
</td>
<td>
148793
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
Parterre Gazonné
</td>
<td>
LITU
</td>
<td>
Liriodendron tulipifera
</td>
<td>
Tulipier de Virginie
</td>
<td>
Tulip Tree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
324049
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
Banquette avec cOpeaux
</td>
<td>
ACFRAB
</td>
<td>
Acer x freemanii 'Autumn Blaze'
</td>
<td>
Érable Autumn Blaze
</td>
<td>
Autumn Blaze Freeman Maple
</td>
<td>
13
</td>
</tr>
<tr>
<td>
R
</td>
<td>
47291
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
PaRterre
</td>
<td>
ACSA
</td>
<td>
Acer saccharinum
</td>
<td>
Érable argenté
</td>
<td>
Silver Maple
</td>
<td>
80
</td>
</tr>
<tr>
<td>
R
</td>
<td>
47560
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
Parterre Gazonné
</td>
<td>
ACPL
</td>
<td>
Acer platanoides
</td>
<td>
Érable de Norvège
</td>
<td>
Norway Maple
</td>
<td>
66
</td>
</tr>
<tr>
<td>
R
</td>
<td>
20978
</td>
<td>
4
</td>
<td>
Mercier - Hochelaga-Maisonneuve
</td>
<td>
Parterre aMénagé
</td>
<td>
ACSC
</td>
<td>
Acer saccharum
</td>
<td>
Érable à sucre
</td>
<td>
Sugar Maple
</td>
<td>
25
</td>
</tr>
<tr>
<td>
H
</td>
<td>
35647
</td>
<td>
25
</td>
<td>
Pierrefonds - Roxboro
</td>
<td>
Parterre Gazonné
</td>
<td>
QURU
</td>
<td>
Quercus rubra
</td>
<td>
Chêne rouge
</td>
<td>
Red Oak
</td>
<td>
31
</td>
</tr>
<tr>
<td>
R
</td>
<td>
661848
</td>
<td>
25
</td>
<td>
Pierrefonds - Roxboro
</td>
<td>
Parterre Gazonné
</td>
<td>
GIBIPS
</td>
<td>
Ginkgo biloba 'Princeton Sentry'
</td>
<td>
Ginkgo à feuilles bilobées Princeton Sentry
</td>
<td>
Princeton Sentry Maidenhair Tree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
231724
</td>
<td>
25
</td>
<td>
Pierrefonds - Roxboro
</td>
<td>
Parterre Gazonné
</td>
<td>
PHAMMA
</td>
<td>
Phellodendron amurensis 'Macho'
</td>
<td>
Phellodendron de l'Amour Macho
</td>
<td>
Macho Amur Cork Tree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
230040
</td>
<td>
25
</td>
<td>
Pierrefonds - Roxboro
</td>
<td>
Parterre Gazonné
</td>
<td>
RUTY
</td>
<td>
Rhus typhina
</td>
<td>
Vinaigrier
</td>
<td>
Staghorn Sumac
</td>
<td>
7
</td>
</tr>
<tr>
<td>
H
</td>
<td>
103001
</td>
<td>
25
</td>
<td>
Pierrefonds - Roxboro
</td>
<td>
Parterre Gazonné
</td>
<td>
ACPL
</td>
<td>
Acer platanoides
</td>
<td>
Érable de Norvège
</td>
<td>
Norway Maple
</td>
<td>
30
</td>
</tr>
<tr>
<td>
H
</td>
<td>
32447
</td>
<td>
25
</td>
<td>
Pierrefonds - Roxboro
</td>
<td>
Parterre Gazonné
</td>
<td>
ACSC
</td>
<td>
Acer saccharum
</td>
<td>
Érable à sucre
</td>
<td>
Sugar Maple
</td>
<td>
18
</td>
</tr>
<tr>
<td>
R
</td>
<td>
153650
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
Parterre Gazonné
</td>
<td>
PRVISC
</td>
<td>
Prunus virginiana 'Schubert'
</td>
<td>
Cerisier de Virginie Schubert
</td>
<td>
Schubert's Chokecherry
</td>
<td>
23
</td>
</tr>
<tr>
<td>
R
</td>
<td>
710823
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
Parterre Gazonné
</td>
<td>
QURU
</td>
<td>
Quercus rubra
</td>
<td>
Chêne rouge
</td>
<td>
Red Oak
</td>
<td>
19
</td>
</tr>
<tr>
<td>
H
</td>
<td>
117384
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
Parterre Gazonné
</td>
<td>
GLTRSK
</td>
<td>
Gleditsia triacanthos 'Skyline'
</td>
<td>
Févier Skyline
</td>
<td>
Skyline Honey-Locust
</td>
<td>
11
</td>
</tr>
<tr>
<td>
R
</td>
<td>
258754
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
Parterre Gazonné
</td>
<td>
GLTRST
</td>
<td>
Gleditsia triacanthos 'Street Keeper'
</td>
<td>
Gleditsia triacanthos 'Street Keeper'
</td>
<td>
Gleditsia triacanthos 'Street Keeper'
</td>
<td>
10
</td>
</tr>
<tr>
<td>
H
</td>
<td>
105163
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
Parterre Gazonné
</td>
<td>
JU
</td>
<td>
Juglans
</td>
<td>
Noyer
</td>
<td>
Walnut, Butternut
</td>
<td>
16
</td>
</tr>
<tr>
<td>
R
</td>
<td>
143129
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
PaRterre
</td>
<td>
POCA
</td>
<td>
Populus x canadensis
</td>
<td>
Peuplier de Caroline
</td>
<td>
Carolina Poplar
</td>
<td>
10
</td>
</tr>
<tr>
<td>
H
</td>
<td>
137106
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
Parterre Gazonné
</td>
<td>
MA
</td>
<td>
Malus
</td>
<td>
Pommier
</td>
<td>
Crab Apple
</td>
<td>
27
</td>
</tr>
<tr>
<td>
R
</td>
<td>
37480
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
PaRterre
</td>
<td>
TICO
</td>
<td>
Tilia cordata
</td>
<td>
Tilleul à petites feuilles
</td>
<td>
Littleleaf European Linden
</td>
<td>
120
</td>
</tr>
<tr>
<td>
H
</td>
<td>
139406
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
Parterre Gazonné
</td>
<td>
AC
</td>
<td>
Acer
</td>
<td>
Érable
</td>
<td>
Maple
</td>
<td>
55
</td>
</tr>
<tr>
<td>
R
</td>
<td>
34412
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
Parterre Gazonné
</td>
<td>
ACSA
</td>
<td>
Acer saccharinum
</td>
<td>
Érable argenté
</td>
<td>
Silver Maple
</td>
<td>
118
</td>
</tr>
<tr>
<td>
R
</td>
<td>
49256
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
Parterre avec Bordure
</td>
<td>
ACPL
</td>
<td>
Acer platanoides
</td>
<td>
Érable de Norvège
</td>
<td>
Norway Maple
</td>
<td>
35
</td>
</tr>
<tr>
<td>
H
</td>
<td>
145863
</td>
<td>
9
</td>
<td>
Rivière-des-Prairies - Pointe-aux-Trembles
</td>
<td>
Parterre Gazonné
</td>
<td>
ACNE
</td>
<td>
Acer negundo
</td>
<td>
Érable à Giguère
</td>
<td>
Manitoba Maple
</td>
<td>
23
</td>
</tr>
<tr>
<td>
H
</td>
<td>
99349
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
Parterre Gazonné
</td>
<td>
ALGLIM
</td>
<td>
Alnus glutinosa 'Imperialis'
</td>
<td>
Aulne glutineux Imperialis
</td>
<td>
Imperialis European Black Alder
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
135026
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
Parterre Gazonné
</td>
<td>
QURU
</td>
<td>
Quercus rubra
</td>
<td>
Chêne rouge
</td>
<td>
Red Oak
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
88855
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
TRottoir
</td>
<td>
FRPE
</td>
<td>
Fraxinus pennsylvanica
</td>
<td>
Frêne de Pennsylvanie
</td>
<td>
Red Ash
</td>
<td>
32
</td>
</tr>
<tr>
<td>
R
</td>
<td>
92064
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
TRottoir
</td>
<td>
GLTRNA
</td>
<td>
Gleditsia triacanthos 'Northern Acclaim'
</td>
<td>
Févier 'Northern Acclaim'
</td>
<td>
Northern Acclaim Honey-Locust
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
710886
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
Parterre Gazonné
</td>
<td>
GLTRIN
</td>
<td>
Gleditsia triacanthos var. inermis
</td>
<td>
Févier inerme d'Amérique
</td>
<td>
Thornless Honey-Locust
</td>
<td>
21
</td>
</tr>
<tr>
<td>
R
</td>
<td>
26978
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
PaRterre
</td>
<td>
CEOC
</td>
<td>
Celtis occidentalis
</td>
<td>
Micocoulier occidental
</td>
<td>
Common Hackberry
</td>
<td>
43
</td>
</tr>
<tr>
<td>
R
</td>
<td>
12611
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
PaRterre
</td>
<td>
ULPU
</td>
<td>
Ulmus pumila
</td>
<td>
Orme de Sibérie
</td>
<td>
Siberian Elm
</td>
<td>
47
</td>
</tr>
<tr>
<td>
R
</td>
<td>
99621
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
TRottoir
</td>
<td>
PYUSPG
</td>
<td>
Pyrus ussuriensis 'Prairie Gem'
</td>
<td>
Poirier de Mandchourie Prairie Gem
</td>
<td>
Prairie Gem Ussurian Pear
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
28091
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
PaRterre
</td>
<td>
TICO
</td>
<td>
Tilia cordata
</td>
<td>
Tilleul à petites feuilles
</td>
<td>
Littleleaf European Linden
</td>
<td>
72
</td>
</tr>
<tr>
<td>
H
</td>
<td>
72487
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
PArc
</td>
<td>
PIPU
</td>
<td>
Picea pungens
</td>
<td>
Épinette du Colorado
</td>
<td>
Colorado Spruce
</td>
<td>
17
</td>
</tr>
<tr>
<td>
R
</td>
<td>
30177
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
Banquette aSphaltée
</td>
<td>
ACSA
</td>
<td>
Acer saccharinum
</td>
<td>
Érable argenté
</td>
<td>
Silver Maple
</td>
<td>
62
</td>
</tr>
<tr>
<td>
R
</td>
<td>
135701
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
TRottoir
</td>
<td>
ACPL
</td>
<td>
Acer platanoides
</td>
<td>
Érable de Norvège
</td>
<td>
Norway Maple
</td>
<td>
20
</td>
</tr>
<tr>
<td>
R
</td>
<td>
89342
</td>
<td>
3
</td>
<td>
Rosemont - La Petite-Patrie
</td>
<td>
PaRterre
</td>
<td>
ACPLEQ
</td>
<td>
Acer platanoides 'Emerald Queen'
</td>
<td>
Érable de Norvège Emerald Queen
</td>
<td>
Emerald Queen Norway Maple
</td>
<td>
33
</td>
</tr>
<tr>
<td>
H
</td>
<td>
101549
</td>
<td>
12
</td>
<td>
Saint-Léonard
</td>
<td>
Parterre Gazonné
</td>
<td>
BEAL
</td>
<td>
Betula alleghaniensis
</td>
<td>
Bouleau jaune
</td>
<td>
Yellow Birch
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
260236
</td>
<td>
12
</td>
<td>
Saint-Léonard
</td>
<td>
Parterre Gazonné
</td>
<td>
FRPE
</td>
<td>
Fraxinus pennsylvanica
</td>
<td>
Frêne de Pennsylvanie
</td>
<td>
Red Ash
</td>
<td>
38
</td>
</tr>
<tr>
<td>
R
</td>
<td>
738988
</td>
<td>
12
</td>
<td>
Saint-Léonard
</td>
<td>
Parterre Gazonné
</td>
<td>
GIBIMA
</td>
<td>
Ginkgo biloba mâle
</td>
<td>
Ginkgo biloba mâle
</td>
<td>
Ginkgo biloba mâle
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
161375
</td>
<td>
12
</td>
<td>
Saint-Léonard
</td>
<td>
Parterre Gazonné
</td>
<td>
CEOC
</td>
<td>
Celtis occidentalis
</td>
<td>
Micocoulier occidental
</td>
<td>
Common Hackberry
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
106803
</td>
<td>
12
</td>
<td>
Saint-Léonard
</td>
<td>
Parterre Gazonné
</td>
<td>
PN
</td>
<td>
Pinus
</td>
<td>
Pin
</td>
<td>
Pine
</td>
<td>
37
</td>
</tr>
<tr>
<td>
H
</td>
<td>
102022
</td>
<td>
12
</td>
<td>
Saint-Léonard
</td>
<td>
Parterre Gazonné
</td>
<td>
TICOGR
</td>
<td>
Tilia cordata 'Greenspire'
</td>
<td>
Tilleul à petites feuilles Greenspire
</td>
<td>
Greenspire Littleleaf Linden
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
108756
</td>
<td>
12
</td>
<td>
Saint-Léonard
</td>
<td>
Parterre Gazonné
</td>
<td>
ACPL
</td>
<td>
Acer platanoides
</td>
<td>
Érable de Norvège
</td>
<td>
Norway Maple
</td>
<td>
45
</td>
</tr>
<tr>
<td>
R
</td>
<td>
203641
</td>
<td>
12
</td>
<td>
Saint-Léonard
</td>
<td>
Parterre Gazonné
</td>
<td>
ACPLCK
</td>
<td>
Acer platanoides 'Crimson King'
</td>
<td>
Érable de Norvège Crimson King
</td>
<td>
Crimson King Norway Maple
</td>
<td>
31
</td>
</tr>
<tr>
<td>
H
</td>
<td>
111291
</td>
<td>
12
</td>
<td>
Saint-Léonard
</td>
<td>
Parterre Gazonné
</td>
<td>
ACSP
</td>
<td>
Acer spicatum
</td>
<td>
Érable à épis
</td>
<td>
Mountain Maple
</td>
<td>
47
</td>
</tr>
<tr>
<td>
H
</td>
<td>
81221
</td>
<td>
16
</td>
<td>
Verdun
</td>
<td>
Parterre Gazonné
</td>
<td>
FRAM
</td>
<td>
Fraxinus americana
</td>
<td>
Frêne d'Amérique
</td>
<td>
White Ash
</td>
<td>
64
</td>
</tr>
<tr>
<td>
H
</td>
<td>
135825
</td>
<td>
16
</td>
<td>
Verdun
</td>
<td>
Parterre Gazonné
</td>
<td>
FAGR
</td>
<td>
Fagus grandifolia
</td>
<td>
Hêtre à grandes feuilles
</td>
<td>
American Beech
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
81722
</td>
<td>
16
</td>
<td>
Verdun
</td>
<td>
Parterre Gazonné
</td>
<td>
POBA
</td>
<td>
Populus balsamifera
</td>
<td>
Peuplier baumier
</td>
<td>
Balsam Poplar
</td>
<td>
21
</td>
</tr>
<tr>
<td>
H
</td>
<td>
82544
</td>
<td>
16
</td>
<td>
Verdun
</td>
<td>
PArc
</td>
<td>
THOC
</td>
<td>
Thuja occidentalis
</td>
<td>
Thuya occidental
</td>
<td>
Eastern White Cedar
</td>
<td>
13
</td>
</tr>
<tr>
<td>
H
</td>
<td>
161758
</td>
<td>
16
</td>
<td>
Verdun
</td>
<td>
Parterre avec Copeaux
</td>
<td>
ACFRAB
</td>
<td>
Acer x freemanii 'Autumn Blaze'
</td>
<td>
Érable Autumn Blaze
</td>
<td>
Autumn Blaze Freeman Maple
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
245891
</td>
<td>
16
</td>
<td>
Verdun
</td>
<td>
Parterre Gazonné
</td>
<td>
ACPL
</td>
<td>
Acer platanoides
</td>
<td>
Érable de Norvège
</td>
<td>
Norway Maple
</td>
<td>
63
</td>
</tr>
<tr>
<td>
H
</td>
<td>
164900
</td>
<td>
6
</td>
<td>
Ville-Marie
</td>
<td>
Parterre Gazonné
</td>
<td>
AMCA
</td>
<td>
Amelanchier canadensis
</td>
<td>
Amélanchier du Canada
</td>
<td>
Downy Serviceberry
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
79732
</td>
<td>
6
</td>
<td>
Ville-Marie
</td>
<td>
Parterre Gazonné
</td>
<td>
GYDI
</td>
<td>
Gymnocladus dioicus
</td>
<td>
Chicot du Canada
</td>
<td>
Kentucky Coffeetree
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
8771
</td>
<td>
6
</td>
<td>
Ville-Marie
</td>
<td>
TRottoir
</td>
<td>
GLTRSH
</td>
<td>
Gleditsia triacanthos 'Shademaster'
</td>
<td>
Févier Shademaster
</td>
<td>
Shademaster Honey-Locust
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
88094
</td>
<td>
6
</td>
<td>
Ville-Marie
</td>
<td>
Parterre Gazonné
</td>
<td>
GLTRIN
</td>
<td>
Gleditsia triacanthos var. inermis
</td>
<td>
Févier inerme d'Amérique
</td>
<td>
Thornless Honey-Locust
</td>
<td>
27
</td>
</tr>
<tr>
<td>
R
</td>
<td>
194260
</td>
<td>
6
</td>
<td>
Ville-Marie
</td>
<td>
TRottoir
</td>
<td>
ULXXMO
</td>
<td>
Ulmus x 'Morton' (Accolade TM)
</td>
<td>
Orme Morton (Accolade TM)
</td>
<td>
Morton (Accolade TM) Elm
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
127074
</td>
<td>
6
</td>
<td>
Ville-Marie
</td>
<td>
Parterre Gazonné
</td>
<td>
PNNIAU
</td>
<td>
Pinus nigra 'Austriaca'
</td>
<td>
Pin noir d'Autriche
</td>
<td>
Austrian Pine
</td>
<td>
30
</td>
</tr>
<tr>
<td>
R
</td>
<td>
243069
</td>
<td>
6
</td>
<td>
Ville-Marie
</td>
<td>
Fond de Trottoir
</td>
<td>
ACFRAB
</td>
<td>
Acer x freemanii 'Autumn Blaze'
</td>
<td>
Érable Autumn Blaze
</td>
<td>
Autumn Blaze Freeman Maple
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
22749
</td>
<td>
6
</td>
<td>
Ville-Marie
</td>
<td>
TRottoir
</td>
<td>
ACPLEQ
</td>
<td>
Acer platanoides 'Emerald Queen'
</td>
<td>
Érable de Norvège Emerald Queen
</td>
<td>
Emerald Queen Norway Maple
</td>
<td>
8
</td>
</tr>
<tr>
<td>
H
</td>
<td>
59028
</td>
<td>
2
</td>
<td>
Villeray-Saint-Michel - Parc-Extension
</td>
<td>
PArc
</td>
<td>
CACA
</td>
<td>
Carpinus caroliniana
</td>
<td>
Charme de Caroline
</td>
<td>
Blue-beech
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
110700
</td>
<td>
2
</td>
<td>
Villeray-Saint-Michel - Parc-Extension
</td>
<td>
TRottoir
</td>
<td>
FRPE
</td>
<td>
Fraxinus pennsylvanica
</td>
<td>
Frêne de Pennsylvanie
</td>
<td>
Red Ash
</td>
<td>
55
</td>
</tr>
<tr>
<td>
R
</td>
<td>
242656
</td>
<td>
2
</td>
<td>
Villeray-Saint-Michel - Parc-Extension
</td>
<td>
Banquette aSphaltée
</td>
<td>
GLTRSK
</td>
<td>
Gleditsia triacanthos 'Skyline'
</td>
<td>
Févier Skyline
</td>
<td>
Skyline Honey-Locust
</td>
<td>
21
</td>
</tr>
<tr>
<td>
H
</td>
<td>
60088
</td>
<td>
2
</td>
<td>
Villeray-Saint-Michel - Parc-Extension
</td>
<td>
PArc
</td>
<td>
SYREIS
</td>
<td>
Syringa reticulata 'Ivory Silk'
</td>
<td>
Lilas japonais Ivory Silk
</td>
<td>
Ivory Silk Japanese Tree Lilac
</td>
<td>
16
</td>
</tr>
<tr>
<td>
H
</td>
<td>
118298
</td>
<td>
2
</td>
<td>
Villeray-Saint-Michel - Parc-Extension
</td>
<td>
Parterre Gazonné
</td>
<td>
ULAMBR
</td>
<td>
Ulmus americana 'Brandon'
</td>
<td>
Orme d'Amérique Brandon
</td>
<td>
Brandon White Elm
</td>
<td>
5
</td>
</tr>
<tr>
<td>
R
</td>
<td>
233769
</td>
<td>
2
</td>
<td>
Villeray-Saint-Michel - Parc-Extension
</td>
<td>
Parterre Gazonné
</td>
<td>
MAXXCE
</td>
<td>
Malus x Centurion®
</td>
<td>
Pommetier Centurion®
</td>
<td>
Centurion® Crab Apple
</td>
<td>
5
</td>
</tr>
<tr>
<td>
H
</td>
<td>
71125
</td>
<td>
2
</td>
<td>
Villeray-Saint-Michel - Parc-Extension
</td>
<td>
PArc
</td>
<td>
TICO
</td>
<td>
Tilia cordata
</td>
<td>
Tilleul à petites feuilles
</td>
<td>
Littleleaf European Linden
</td>
<td>
23
</td>
</tr>
<tr>
<td>
R
</td>
<td>
112500
</td>
<td>
2
</td>
<td>
Villeray-Saint-Michel - Parc-Extension
</td>
<td>
Parterre Gazonné
</td>
<td>
ACSA
</td>
<td>
Acer saccharinum
</td>
<td>
Érable argenté
</td>
<td>
Silver Maple
</td>
<td>
65
</td>
</tr>
<tr>
<td>
R
</td>
<td>
141091
</td>
<td>
2
</td>
<td>
Villeray-Saint-Michel - Parc-Extension
</td>
<td>
TRottoir
</td>
<td>
ACPL
</td>
<td>
Acer platanoides
</td>
<td>
Érable de Norvège
</td>
<td>
Norway Maple
</td>
<td>
19
</td>
</tr>
<tr>
<td>
R
</td>
<td>
640545
</td>
<td>
2
</td>
<td>
Villeray-Saint-Michel - Parc-Extension
</td>
<td>
Parterre Gazonné
</td>
<td>
ACRURE
</td>
<td>
Acer rubrum 'Frank Jr.. (Redpointe TM)
</td>
<td>
érable rouge Redpointe
</td>
<td>
Redpointe Maple
</td>
<td>
5
</td>
</tr>
</tbody>
</table>
</div>
<div class="dataset-datatable-pager">
<button type="button" data-dataset-prev="">
Précédent
</button>
<span data-dataset-page=""></span><button type="button" data-dataset-next="">Suivant</button>
</div>
</div>
<div class="dataset-preview-chart">
<span class="dataset-panel-label">Aperçu graphique</span><svg class="dataset-r-chart" viewbox="0 0 320 210" role="img" aria-label="Aperçu numérique généré par R"><line x1="34" y1="158" x2="292" y2="158" class="dataset-svg-axis"></line><line x1="34" y1="36" x2="34" y2="158" class="dataset-svg-axis"></line><polyline points="34,87.8 40.4,158 46.7,46 53.1,137.9 59.4,62.7 65.8,132.9 72.2,111.2 78.5,158 84.9,102.8 91.2,158 97.6,158 103.9,104.5 110.3,158 116.7,91.1 123,114.5 129.4,87.8 135.7,59.4 142.1,158 148.5,131.3 154.8,144.6 161.2,158 167.5,61 173.9,158 180.3,158 186.6,158 193,121.2 199.3,158 205.7,116.2 212.1,158 218.4,153 224.8,158 231.1,74.4 237.5,131.3 243.8,139.6 250.2,158 256.6,158 262.9,127.9 269.3,57.7 275.6,134.6 282,158" class="dataset-svg-line"></polyline><circle cx="34" cy="87.8" r="3.2" class="dataset-svg-point"></circle><circle cx="40.4" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="46.7" cy="46" r="3.2" class="dataset-svg-point"></circle><circle cx="53.1" cy="137.9" r="3.2" class="dataset-svg-point"></circle><circle cx="59.4" cy="62.7" r="3.2" class="dataset-svg-point"></circle><circle cx="65.8" cy="132.9" r="3.2" class="dataset-svg-point"></circle><circle cx="72.2" cy="111.2" r="3.2" class="dataset-svg-point"></circle><circle cx="78.5" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="84.9" cy="102.8" r="3.2" class="dataset-svg-point"></circle><circle cx="91.2" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="97.6" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="103.9" cy="104.5" r="3.2" class="dataset-svg-point"></circle><circle cx="110.3" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="116.7" cy="91.1" r="3.2" class="dataset-svg-point"></circle><circle cx="123" cy="114.5" r="3.2" class="dataset-svg-point"></circle><circle cx="129.4" cy="87.8" r="3.2" class="dataset-svg-point"></circle><circle cx="135.7" cy="59.4" r="3.2" class="dataset-svg-point"></circle><circle cx="142.1" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="148.5" cy="131.3" r="3.2" class="dataset-svg-point"></circle><circle cx="154.8" cy="144.6" r="3.2" class="dataset-svg-point"></circle><circle cx="161.2" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="167.5" cy="61" r="3.2" class="dataset-svg-point"></circle><circle cx="173.9" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="180.3" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="186.6" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="193" cy="121.2" r="3.2" class="dataset-svg-point"></circle><circle cx="199.3" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="205.7" cy="116.2" r="3.2" class="dataset-svg-point"></circle><circle cx="212.1" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="218.4" cy="153" r="3.2" class="dataset-svg-point"></circle><circle cx="224.8" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="231.1" cy="74.4" r="3.2" class="dataset-svg-point"></circle><circle cx="237.5" cy="131.3" r="3.2" class="dataset-svg-point"></circle><circle cx="243.8" cy="139.6" r="3.2" class="dataset-svg-point"></circle><circle cx="250.2" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="256.6" cy="158" r="3.2" class="dataset-svg-point"></circle><circle cx="262.9" cy="127.9" r="3.2" class="dataset-svg-point"></circle><circle cx="269.3" cy="57.7" r="3.2" class="dataset-svg-point"></circle><circle cx="275.6" cy="134.6" r="3.2" class="dataset-svg-point"></circle><circle cx="282" cy="158" r="3.2" class="dataset-svg-point"></circle><text x="34" y="24" class="dataset-svg-title">dhp</text><text x="34" y="186" class="dataset-svg-label">5</text><text x="230" y="186" class="dataset-svg-label">72</text><text x="34" y="202" class="dataset-svg-label">1</text><text x="250" y="202" class="dataset-svg-label">40</text></svg>
</div>
</div>
<div class="dataset-variable-panel">
<span class="dataset-panel-label">Variables à repérer</span>
<div class="dataset-variable-list">
<span class="dataset-variable-chip">inventaire_type</span><span class="dataset-variable-chip">arbre_id</span><span class="dataset-variable-chip">arrondissement_code</span><span class="dataset-variable-chip">arrondissement</span><span class="dataset-variable-chip">emplacement</span><span class="dataset-variable-chip">sigle</span><span class="dataset-variable-chip">essence_latin</span>
</div>
<div class="dataset-simple-facts">
<div class="dataset-simple-fact">
<span>Territoire</span><strong>Montréal</strong>
</div>
<div class="dataset-simple-fact">
<span>Niveau</span><strong>Introduction à intermédiaire</strong>
</div>
<div class="dataset-simple-fact">
<span>Format</span><strong>CSV officiel préparé localement; historique DHP et dictionnaire PDF disponibles à la source</strong>
</div>
</div>
</div>
</div>
</section>
<details class="dataset-doc-panel" id="documentation">
<summary>
<span>Documentation complète</span><strong>Sources, variables, code R minimal, méthode et limites</strong>
</summary>
<div class="dataset-detail-content">
<section id="pourquoi-ce-jeu-est-intéressant" class="level2">
<h2 class="anchored" data-anchor-id="pourquoi-ce-jeu-est-intéressant">Pourquoi ce jeu est intéressant</h2>
<p>Ce jeu est très riche pour l’enseignement : il relie essences, mesures dendrométriques, arrondissement, emplacement, localisation et qualité des données. Il permet de travailler des questions concrètes de foresterie urbaine avec une vraie source municipale.</p>
<p>Il est aussi utile parce qu’il contient des difficultés réalistes : gros fichier, plusieurs ressources, valeurs manquantes, dates aberrantes et mise en garde officielle sur la précision des localisations.</p>
<p>Question d’analyse : quelles essences d’arbres publics dominent l’inventaire, et quelles limites faut-il vérifier avant de cartographier ou comparer les arrondissements?</p>
</section>
<section id="ce-qui-a-été-vérifié" class="level2">
<h2 class="anchored" data-anchor-id="ce-qui-a-été-vérifié">Ce qui a été vérifié</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Élément</th>
<th>Résultat vérifié</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Paquet CKAN</td>
<td><code>b89fd27d-4b49-461b-8e54-fa2b34a628c4</code></td>
</tr>
<tr class="even">
<td>Source officielle</td>
<td>Données Québec / Ville de Montréal</td>
</tr>
<tr class="odd">
<td>Ressources dans le paquet</td>
<td>6 ressources</td>
</tr>
<tr class="even">
<td>Ressource préparée ici</td>
<td><code>arbres-publics.csv</code></td>
</tr>
<tr class="odd">
<td>Licence</td>
<td>Attribution (CC-BY 4.0), selon les métadonnées CKAN consultées le 2026-06-21</td>
</tr>
<tr class="even">
<td>Dernière modification du paquet CKAN</td>
<td>2026-06-21</td>
</tr>
<tr class="odd">
<td>Dernière modification du CSV consolidé</td>
<td>2026-06-21</td>
</tr>
<tr class="even">
<td>Table préparée</td>
<td><code>data/processed/arbres-publics-montreal/arbres_publics_montreal.csv</code></td>
</tr>
<tr class="odd">
<td>Résumés préparés</td>
<td>ressources, essences, arrondissements, emplacements, valeurs manquantes, qualité des dates</td>
</tr>
</tbody>
</table>
</section>
<section id="source-et-conditions" class="level2">
<h2 class="anchored" data-anchor-id="source-et-conditions">Source et conditions</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Champ</th>
<th>Information</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Page Données Québec</td>
<td><a href="https://www.donneesquebec.ca/recherche/dataset/vmtl-arbres" class="uri">https://www.donneesquebec.ca/recherche/dataset/vmtl-arbres</a></td>
</tr>
<tr class="even">
<td>API CKAN</td>
<td><a href="https://www.donneesquebec.ca/recherche/api/3/action/package_show?id=vmtl-arbres" class="uri">https://www.donneesquebec.ca/recherche/api/3/action/package_show?id=vmtl-arbres</a></td>
</tr>
<tr class="odd">
<td>CSV consolidé</td>
<td><a href="https://donnees.montreal.ca/dataset/b89fd27d-4b49-461b-8e54-fa2b34a628c4/resource/64e28fe6-ef37-437a-972d-d1d3f1f7d891/download/arbres-publics.csv" class="uri">https://donnees.montreal.ca/dataset/b89fd27d-4b49-461b-8e54-fa2b34a628c4/resource/64e28fe6-ef37-437a-972d-d1d3f1f7d891/download/arbres-publics.csv</a></td>
</tr>
<tr class="even">
<td>Historique DHP</td>
<td><a href="https://donnees.montreal.ca/dataset/b89fd27d-4b49-461b-8e54-fa2b34a628c4/resource/6c217c92-63c8-49e8-a6ef-afda6121656d/download/arbres-dhp.csv" class="uri">https://donnees.montreal.ca/dataset/b89fd27d-4b49-461b-8e54-fa2b34a628c4/resource/6c217c92-63c8-49e8-a6ef-afda6121656d/download/arbres-dhp.csv</a></td>
</tr>
<tr class="odd">
<td>Dictionnaire PDF</td>
<td><a href="https://donnees.montreal.ca/dataset/b89fd27d-4b49-461b-8e54-fa2b34a628c4/resource/7fe8c742-ee64-4cca-b889-467b68e7db6a/download/dictionnaire-de-donnees-arbres-publics_rev2018.pdf" class="uri">https://donnees.montreal.ca/dataset/b89fd27d-4b49-461b-8e54-fa2b34a628c4/resource/7fe8c742-ee64-4cca-b889-467b68e7db6a/download/dictionnaire-de-donnees-arbres-publics_rev2018.pdf</a></td>
</tr>
<tr class="even">
<td>Territoire</td>
<td>Montréal</td>
</tr>
<tr class="odd">
<td>Date d’accès</td>
<td>2026-06-21</td>
</tr>
</tbody>
</table>
<p>La description officielle indique que les données portent sur les arbres municipaux du domaine public, incluant des arbres de rue et hors rue. Elle signale aussi que les localisations spatiales peuvent être imprécises ou pas à jour et que certains arrondissements n’indiquent pas les arbres de parcs.</p>
</section>
<section id="ce-que-représente-une-ligne" class="level2">
<h2 class="anchored" data-anchor-id="ce-que-représente-une-ligne">Ce que représente une ligne</h2>
<p>Une ligne représente un arbre public inventorié dans le fichier consolidé. La ligne contient des informations d’arrondissement, d’emplacement, d’essence, de diamètre, de dates et de coordonnées.</p>
<p>Une ligne n’est pas une mesure écologique complète, un arbre privé, ni une preuve que le couvert arboré est mesuré de façon uniforme dans tous les arrondissements.</p>
</section>
<section id="variables-principales" class="level2">
<h2 class="anchored" data-anchor-id="variables-principales">Variables principales</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable préparée</th>
<th>Rôle</th>
<th>Point de vigilance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>arrondissement</code></td>
<td>Arrondissement publié</td>
<td>13 arrondissements dans le fichier consolidé</td>
</tr>
<tr class="even">
<td><code>emplacement</code></td>
<td>Type d’emplacement</td>
<td>Libellés hétérogènes à nettoyer selon la question</td>
</tr>
<tr class="odd">
<td><code>essence_fr</code></td>
<td>Nom français de l’essence</td>
<td>795 valeurs distinctes non manquantes</td>
</tr>
<tr class="even">
<td><code>essence_latin</code></td>
<td>Nom latin</td>
<td>Utile pour regrouper ou valider les noms</td>
</tr>
<tr class="odd">
<td><code>dhp</code></td>
<td>Diamètre à hauteur de poitrine</td>
<td>Médiane observée : 19</td>
</tr>
<tr class="even">
<td><code>date_releve_plausible</code></td>
<td>Date de relevé après contrôle minimal</td>
<td>39 dates de relevé non plausibles selon la règle de préparation</td>
</tr>
<tr class="odd">
<td><code>date_plantation_plausible</code></td>
<td>Date de plantation après contrôle minimal</td>
<td>40,2 % des dates de plantation sont manquantes</td>
</tr>
<tr class="even">
<td><code>longitude</code>, <code>latitude</code></td>
<td>Coordonnées publiées</td>
<td>2 lignes sans coordonnées</td>
</tr>
<tr class="odd">
<td><code>coordonnees_disponibles</code></td>
<td>Indicateur préparé</td>
<td>Ne garantit pas que la localisation est exacte</td>
</tr>
</tbody>
</table>
</section>
<section id="résultats-r" class="level2">
<h2 class="anchored" data-anchor-id="résultats-r">RÉSULTATS R</h2>
<p>Les résultats ci-dessous proviennent de <code>preparation.R</code>, exécuté sur le CSV téléchargé le 2026-06-21.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Indicateur</th>
<th style="text-align: right;">Valeur</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ressources CKAN documentées</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td>Lignes dans le CSV source</td>
<td style="text-align: right;">334 464</td>
</tr>
<tr class="odd">
<td>Colonnes dans le CSV source</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="even">
<td>Lignes préparées</td>
<td style="text-align: right;">334 464</td>
</tr>
<tr class="odd">
<td>Colonnes préparées</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="even">
<td>Arrondissements</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="odd">
<td>Essences françaises non manquantes</td>
<td style="text-align: right;">795</td>
</tr>
<tr class="even">
<td>Essences latines non manquantes</td>
<td style="text-align: right;">799</td>
</tr>
<tr class="odd">
<td>Emplacements distincts</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="even">
<td>Coordonnées manquantes</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td>Dates de plantation manquantes</td>
<td style="text-align: right;">134 514</td>
</tr>
<tr class="even">
<td>DHP manquants</td>
<td style="text-align: right;">141</td>
</tr>
<tr class="odd">
<td>DHP médian</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td>Arbres remarquables</td>
<td style="text-align: right;">159</td>
</tr>
</tbody>
</table>
</section>
<section id="essences-les-plus-fréquentes" class="level2">
<h2 class="anchored" data-anchor-id="essences-les-plus-fréquentes">Essences les plus fréquentes</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Essence française</th>
<th style="text-align: right;">Arbres</th>
<th style="text-align: right;">Pourcentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Érable argenté</td>
<td style="text-align: right;">29 613</td>
<td style="text-align: right;">8,9 %</td>
</tr>
<tr class="even">
<td>Érable de Norvège</td>
<td style="text-align: right;">22 735</td>
<td style="text-align: right;">6,8 %</td>
</tr>
<tr class="odd">
<td>Frêne de Pennsylvanie</td>
<td style="text-align: right;">14 012</td>
<td style="text-align: right;">4,2 %</td>
</tr>
<tr class="even">
<td>Tilleul à petites feuilles</td>
<td style="text-align: right;">13 303</td>
<td style="text-align: right;">4,0 %</td>
</tr>
<tr class="odd">
<td>Micocoulier occidental</td>
<td style="text-align: right;">10 143</td>
<td style="text-align: right;">3,0 %</td>
</tr>
<tr class="even">
<td>Chicot du Canada</td>
<td style="text-align: right;">10 075</td>
<td style="text-align: right;">3,0 %</td>
</tr>
<tr class="odd">
<td>Févier Skyline</td>
<td style="text-align: right;">9 851</td>
<td style="text-align: right;">2,9 %</td>
</tr>
<tr class="even">
<td>Févier inerme d’Amérique</td>
<td style="text-align: right;">8 259</td>
<td style="text-align: right;">2,5 %</td>
</tr>
<tr class="odd">
<td>Épinette du Colorado</td>
<td style="text-align: right;">6 752</td>
<td style="text-align: right;">2,0 %</td>
</tr>
<tr class="even">
<td>Orme Morton (Accolade TM)</td>
<td style="text-align: right;">6 036</td>
<td style="text-align: right;">1,8 %</td>
</tr>
</tbody>
</table>
<p>Cette table est une description de l’inventaire consolidé, pas une mesure complète de la biodiversité urbaine.</p>
</section>
<section id="arrondissements-avec-le-plus-darbres" class="level2">
<h2 class="anchored" data-anchor-id="arrondissements-avec-le-plus-darbres">Arrondissements avec le plus d’arbres</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Arrondissement</th>
<th style="text-align: right;">Arbres</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mercier - Hochelaga-Maisonneuve</td>
<td style="text-align: right;">38 076</td>
</tr>
<tr class="even">
<td>Rosemont - La Petite-Patrie</td>
<td style="text-align: right;">37 309</td>
</tr>
<tr class="odd">
<td>Ahuntsic - Cartierville</td>
<td style="text-align: right;">36 672</td>
</tr>
<tr class="even">
<td>Rivière-des-Prairies - Pointe-aux-Trembles</td>
<td style="text-align: right;">34 619</td>
</tr>
<tr class="odd">
<td>Côte-des-Neiges - Notre-Dame-de-Grâce</td>
<td style="text-align: right;">29 096</td>
</tr>
<tr class="even">
<td>Villeray-Saint-Michel - Parc-Extension</td>
<td style="text-align: right;">27 279</td>
</tr>
<tr class="odd">
<td>Saint-Léonard</td>
<td style="text-align: right;">23 381</td>
</tr>
<tr class="even">
<td>Le Sud-Ouest</td>
<td style="text-align: right;">22 657</td>
</tr>
</tbody>
</table>
<p>Cette comparaison dépend de la couverture d’inventaire, des arbres de parcs inclus ou non, et de la taille des arrondissements.</p>
</section>
<section id="qualité-des-dates" class="level2">
<h2 class="anchored" data-anchor-id="qualité-des-dates">Qualité des dates</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: right;">Valeurs manquantes</th>
<th style="text-align: right;">Dates non plausibles</th>
<th>Première date plausible</th>
<th>Dernière date plausible</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>date_releve</code></td>
<td style="text-align: right;">141</td>
<td style="text-align: right;">39</td>
<td>1900-01-01</td>
<td>2026-06-19</td>
</tr>
<tr class="even">
<td><code>date_plantation</code></td>
<td style="text-align: right;">134 514</td>
<td style="text-align: right;">16</td>
<td>1901-08-21</td>
<td>2026-06-19</td>
</tr>
</tbody>
</table>
<p>La règle de plausibilité utilisée dans <code>preparation.R</code> conserve les dates entre 1900-01-01 et la date d’accès. Elle ne remplace pas une validation municipale, mais elle permet de rendre les anomalies visibles.</p>
</section>
<section id="valeurs-manquantes-principales" class="level2">
<h2 class="anchored" data-anchor-id="valeurs-manquantes-principales">Valeurs manquantes principales</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: right;">Valeurs manquantes</th>
<th style="text-align: right;">Pourcentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>code_parc</code></td>
<td style="text-align: right;">218 220</td>
<td style="text-align: right;">65,24 %</td>
</tr>
<tr class="even">
<td><code>nom_parc</code></td>
<td style="text-align: right;">218 220</td>
<td style="text-align: right;">65,24 %</td>
</tr>
<tr class="odd">
<td><code>code_secteur</code></td>
<td style="text-align: right;">218 220</td>
<td style="text-align: right;">65,24 %</td>
</tr>
<tr class="even">
<td><code>nom_secteur</code></td>
<td style="text-align: right;">218 220</td>
<td style="text-align: right;">65,24 %</td>
</tr>
<tr class="odd">
<td><code>stationnement_heure</code></td>
<td style="text-align: right;">201 615</td>
<td style="text-align: right;">60,28 %</td>
</tr>
<tr class="even">
<td><code>distance_ligne_rue</code></td>
<td style="text-align: right;">193 641</td>
<td style="text-align: right;">57,90 %</td>
</tr>
<tr class="odd">
<td><code>stationnement_jour</code></td>
<td style="text-align: right;">193 322</td>
<td style="text-align: right;">57,80 %</td>
</tr>
<tr class="even">
<td><code>no_civique</code></td>
<td style="text-align: right;">163 357</td>
<td style="text-align: right;">48,84 %</td>
</tr>
<tr class="odd">
<td><code>distance_pave</code></td>
<td style="text-align: right;">140 454</td>
<td style="text-align: right;">41,99 %</td>
</tr>
<tr class="even">
<td><code>date_plantation</code></td>
<td style="text-align: right;">134 514</td>
<td style="text-align: right;">40,22 %</td>
</tr>
</tbody>
</table>
<p>Les valeurs manquantes ne sont pas un défaut uniforme. Elles reflètent en partie la structure même du fichier, par exemple des variables pertinentes surtout pour certains types d’emplacement.</p>
</section>
<section id="lecture-statistique" class="level2">
<h2 class="anchored" data-anchor-id="lecture-statistique">Lecture statistique</h2>
<p>Une analyse prudente suit cet ordre :</p>
<ol type="1">
<li>vérifier si la question porte sur les arbres de rue, les arbres hors rue, les parcs ou l’ensemble consolidé;</li>
<li>inspecter les valeurs manquantes avant de comparer les arrondissements;</li>
<li>traiter les dates de plantation et de relevé comme des variables à valider;</li>
<li>compter les essences avec regroupement explicite des libellés manquants;</li>
<li>cartographier avec une note sur la précision des localisations;</li>
<li>éviter de conclure sur le couvert arboré ou la biodiversité sans données complémentaires.</li>
</ol>
<p>Les données permettent de décrire un inventaire municipal riche. Elles ne suffisent pas, seules, à estimer la canopée, la santé des arbres ou l’équité environnementale.</p>
</section>
<section id="concepts-enseignables" class="level2">
<h2 class="anchored" data-anchor-id="concepts-enseignables">Concepts enseignables</h2>
<ul>
<li>importation d’un gros CSV;</li>
<li>catégories et libellés;</li>
<li>valeurs manquantes;</li>
<li>dates aberrantes;</li>
<li>statistiques descriptives;</li>
<li>cartographie responsable;</li>
<li>qualité des données;</li>
<li>limites d’un inventaire administratif.</li>
</ul>
</section>
<section id="score-zéro-déchet" class="level2">
<h2 class="anchored" data-anchor-id="score-zéro-déchet">Score zéro déchet</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th style="text-align: right;">Score</th>
<th>Justification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Contexte québécois</td>
<td style="text-align: right;">3</td>
<td>Inventaire municipal montréalais</td>
</tr>
<tr class="even">
<td>Accessibilité pédagogique</td>
<td style="text-align: right;">3</td>
<td>Variables concrètes et interprétables</td>
</tr>
<tr class="odd">
<td>Qualité documentaire</td>
<td style="text-align: right;">3</td>
<td>Page Données Québec, API CKAN et dictionnaire PDF</td>
</tr>
<tr class="even">
<td>Potentiel de nettoyage</td>
<td style="text-align: right;">3</td>
<td>Dates, libellés, valeurs manquantes et coordonnées</td>
</tr>
<tr class="odd">
<td>Potentiel de visualisation</td>
<td style="text-align: right;">3</td>
<td>Cartes, barres, boîtes à moustaches</td>
</tr>
<tr class="even">
<td>Potentiel de statistique descriptive</td>
<td style="text-align: right;">3</td>
<td>Résumés naturels par arrondissement et essence</td>
</tr>
<tr class="odd">
<td>Potentiel d’inférence</td>
<td style="text-align: right;">2</td>
<td>Possible avec prudence et données complémentaires</td>
</tr>
<tr class="even">
<td>Potentiel de modélisation</td>
<td style="text-align: right;">2</td>
<td>Modélisation exploratoire possible mais encadrée</td>
</tr>
<tr class="odd">
<td>Potentiel éthique</td>
<td style="text-align: right;">2</td>
<td>Risques liés à la représentation territoriale</td>
</tr>
<tr class="even">
<td>Réutilisabilité</td>
<td style="text-align: right;">3</td>
<td>Utile en importation, EDA, spatial et qualité des données</td>
</tr>
</tbody>
</table>
<p>Total : 27 sur 30.</p>
</section>
<section id="activité-courte" class="level2">
<h2 class="anchored" data-anchor-id="activité-courte">Activité courte</h2>
<p>En 30 à 45 minutes, compter les essences principales dans un arrondissement et nommer une limite de couverture.</p>
</section>
<section id="activité-longue" class="level2">
<h2 class="anchored" data-anchor-id="activité-longue">Activité longue</h2>
<p>En 2 à 3 heures, produire une carte agrégée ou un échantillon cartographique, un tableau de valeurs manquantes et une analyse par arrondissement.</p>
</section>
<section id="code-r-minimal" class="level2">
<h2 class="anchored" data-anchor-id="code-r-minimal">Code R minimal</h2>
<p>À exécuter depuis la racine du projet.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Download and prepare official CSV resource</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"datasets/arbres-publics-montreal/preparation.R"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Import prepared data</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>arbres <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/processed/arbres-publics-montreal/arbres_publics_montreal.csv"</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarise top species in one borough</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>resume_essences <span class="ot">&lt;-</span> arbres <span class="sc">|&gt;</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(arrondissement <span class="sc">==</span> <span class="st">"Rosemont - La Petite-Patrie"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(essence_fr, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>resume_essences</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot top species</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resume_essences, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(essence_fr, n), <span class="at">y =</span> n)) <span class="sc">+</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Essence"</span>,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Nombre d'arbres"</span>,</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Essences les plus fréquentes dans Rosemont - La Petite-Patrie"</span>,</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Inventaire public municipal; vérifier la couverture avant comparaison"</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="limites-et-précautions" class="level2">
<h2 class="anchored" data-anchor-id="limites-et-précautions">Limites et précautions</h2>
<ul>
<li>La source officielle signale que certaines localisations peuvent être imprécises ou pas à jour.</li>
<li>Dans certains arrondissements, les arbres de parcs ne sont pas indiqués selon la description officielle.</li>
<li>Les dates de plantation sont manquantes pour 134 514 lignes.</li>
<li>Les dates préparées plausibles reposent sur une règle de nettoyage, pas sur une validation administrative indépendante.</li>
<li>Comparer les arrondissements exige de tenir compte de la superficie, de la densité, de la couverture d’inventaire et des arbres privés.</li>
</ul>
</section>
<section id="extensions" class="level2">
<h2 class="anchored" data-anchor-id="extensions">Extensions</h2>
<ul>
<li>Comparer les essences dominantes entre deux arrondissements.</li>
<li>Étudier les valeurs manquantes par type d’emplacement.</li>
<li>Construire un graphique du DHP par essence fréquente.</li>
<li>Produire une carte en échantillonnant les points ou en les agrégeant par grille.</li>
<li>Joindre des données de superficie ou de population pour construire un indicateur contextualisé.</li>
</ul>
</section>
<section id="références-utilisées" class="level2">
<h2 class="anchored" data-anchor-id="références-utilisées">Références utilisées</h2>
<ul>
<li>Données Québec. 2026. Arbres publics sur le territoire de la Ville. <a href="https://www.donneesquebec.ca/recherche/dataset/vmtl-arbres" class="uri">https://www.donneesquebec.ca/recherche/dataset/vmtl-arbres</a></li>
<li>Données Québec. 2026. API CKAN du paquet Arbres publics sur le territoire de la Ville. <a href="https://www.donneesquebec.ca/recherche/api/3/action/package_show?id=vmtl-arbres" class="uri">https://www.donneesquebec.ca/recherche/api/3/action/package_show?id=vmtl-arbres</a></li>
<li>Ville de Montréal. 2026. Inventaire arbres publics, fichier consolidé. <a href="https://donnees.montreal.ca/dataset/b89fd27d-4b49-461b-8e54-fa2b34a628c4/resource/64e28fe6-ef37-437a-972d-d1d3f1f7d891/download/arbres-publics.csv" class="uri">https://donnees.montreal.ca/dataset/b89fd27d-4b49-461b-8e54-fa2b34a628c4/resource/64e28fe6-ef37-437a-972d-d1d3f1f7d891/download/arbres-publics.csv</a></li>
<li>Ville de Montréal. 2026. Dictionnaire de données des arbres publics. <a href="https://donnees.montreal.ca/dataset/b89fd27d-4b49-461b-8e54-fa2b34a628c4/resource/7fe8c742-ee64-4cca-b889-467b68e7db6a/download/dictionnaire-de-donnees-arbres-publics_rev2018.pdf" class="uri">https://donnees.montreal.ca/dataset/b89fd27d-4b49-461b-8e54-fa2b34a628c4/resource/7fe8c742-ee64-4cca-b889-467b68e7db6a/download/dictionnaire-de-donnees-arbres-publics_rev2018.pdf</a></li>
</ul>
</section>
</div>
</details>
<section class="dataset-activities-panel" id="activites-pedagogiques">
<div class="dataset-section-heading">
<span>Activités pédagogiques</span>
<h2 class="anchored">
Pour aller plus loin
</h2>
</div>
<div class="dataset-activity-grid">
<a class="dataset-activity-card" href="activite-courte.html">
<div class="dataset-activity-meta">
<span>30-45 minutes</span><span>Introductif</span><span class="dataset-activity-status">Prête à enseigner</span>
</div>
<strong>Essences d'arbres par arrondissement</strong>
<p>
Quelles essences d'arbres publics sont les plus fréquentes dans un arrondissement choisi?
</p>
<div class="dataset-activity-chips">
<span class="dataset-activity-chip">Laboratoire</span><span class="dataset-activity-chip">Exploration de données</span>
</div>
<p class="dataset-activity-output">
À produire : Un tableau ou graphique descriptif accompagné de trois phrases d'interprétation prudente.
</p>
</a> <a class="dataset-activity-card" href="activite-longue.html">
<div class="dataset-activity-meta">
<span>2-3 heures</span><span>Intermédiaire</span><span class="dataset-activity-status">Prête à enseigner</span>
</div>
<strong>Carte et qualité des données des arbres publics</strong>
<p>
Comment cartographier ou résumer un inventaire d'arbres publics tout en montrant ses limites?
</p>
<div class="dataset-activity-chips">
<span class="dataset-activity-chip">Mini-projet</span><span class="dataset-activity-chip">Étude de cas</span>
</div>
<p class="dataset-activity-output">
À produire : Un court rapport reproductible avec contexte, tableau ou graphique, interprétation et limites.
</p>
</a>
</div>
</section>
</section>
<script>
(function() {
  function normalize(value) {
    return (value || '').toString().toLocaleLowerCase('fr-CA');
  }
  function numericValue(value) {
    var cleaned = (value || '').toString().replace(/\s/g, '').replace(',', '.');
    if (!/^[-+]?\d*(\.\d+)?$/.test(cleaned) || cleaned === '' || cleaned === '-' || cleaned === '+') {
      return null;
    }
    var parsed = Number(cleaned);
    return Number.isFinite(parsed) ? parsed : null;
  }
  function initDatatable(root) {
    if (root.dataset.enhanced === 'true') return;
    root.dataset.enhanced = 'true';
    var table = root.querySelector('table');
    var tbody = root.querySelector('tbody');
    if (!table || !tbody) return;
    var rows = Array.from(tbody.querySelectorAll('tr'));
    var search = root.querySelector('[data-dataset-search]');
    var pageSize = root.querySelector('[data-dataset-page-size]');
    var count = root.querySelector('[data-dataset-count]');
    var page = root.querySelector('[data-dataset-page]');
    var prev = root.querySelector('[data-dataset-prev]');
    var next = root.querySelector('[data-dataset-next]');
    var sortButtons = Array.from(root.querySelectorAll('[data-dataset-sort]'));
    var state = { query: '', size: 10, page: 1, sortCol: null, sortDir: 1 };
    function filteredRows() {
      var query = normalize(state.query);
      var filtered = query === '' ? rows.slice() : rows.filter(function(row) {
        return normalize(row.textContent).indexOf(query) !== -1;
      });
      if (state.sortCol !== null) {
        filtered.sort(function(a, b) {
          var av = a.children[state.sortCol] ? a.children[state.sortCol].textContent.trim() : '';
          var bv = b.children[state.sortCol] ? b.children[state.sortCol].textContent.trim() : '';
          var an = numericValue(av);
          var bn = numericValue(bv);
          var result;
          if (an !== null && bn !== null) {
            result = an - bn;
          } else {
            result = normalize(av).localeCompare(normalize(bv), 'fr-CA', { numeric: true });
          }
          return result * state.sortDir;
        });
      }
      return filtered;
    }
    function render() {
      var filtered = filteredRows();
      var totalPages = Math.max(1, Math.ceil(filtered.length / state.size));
      state.page = Math.min(Math.max(1, state.page), totalPages);
      var start = (state.page - 1) * state.size;
      var visible = filtered.slice(start, start + state.size);
      filtered.forEach(function(row) { tbody.appendChild(row); });
      rows.filter(function(row) { return filtered.indexOf(row) === -1; }).forEach(function(row) { tbody.appendChild(row); });
      rows.forEach(function(row) { row.hidden = true; });
      visible.forEach(function(row) { row.hidden = false; });
      if (count) count.textContent = filtered.length + ' ligne' + (filtered.length > 1 ? 's' : '');
      if (page) page.textContent = 'Page ' + state.page + ' / ' + totalPages;
      if (prev) prev.disabled = state.page <= 1;
      if (next) next.disabled = state.page >= totalPages;
      sortButtons.forEach(function(button) {
        var indicator = button.querySelector('span');
        if (!indicator) return;
        var col = Number(button.dataset.datasetSort);
        indicator.textContent = col === state.sortCol ? (state.sortDir === 1 ? ' ↑' : ' ↓') : '';
      });
    }
    if (search) {
      search.addEventListener('input', function(event) {
        state.query = event.target.value;
        state.page = 1;
        render();
      });
    }
    if (pageSize) {
      state.size = Number(pageSize.value) || 10;
      pageSize.addEventListener('change', function(event) {
        state.size = Number(event.target.value) || 10;
        state.page = 1;
        render();
      });
    }
    if (prev) prev.addEventListener('click', function() { state.page -= 1; render(); });
    if (next) next.addEventListener('click', function() { state.page += 1; render(); });
    sortButtons.forEach(function(button) {
      button.addEventListener('click', function() {
        var col = Number(button.dataset.datasetSort);
        if (state.sortCol === col) {
          state.sortDir = state.sortDir * -1;
        } else {
          state.sortCol = col;
          state.sortDir = 1;
        }
        state.page = 1;
        render();
      });
    });
    render();
  }
  function initDocumentationPanel() {
    var panel = document.getElementById('documentation');
    if (!panel) return;
    function openForHash() {
      if (!window.location.hash) return;
      var id = window.location.hash.slice(1);
      if (id === 'documentation') {
        panel.open = true;
        return;
      }
      var target = document.getElementById(id);
      if (target && panel.contains(target)) panel.open = true;
    }
    window.addEventListener('hashchange', openForHash);
    openForHash();
  }
  function initAll() {
    initDocumentationPanel();
    document.querySelectorAll('.dataset-datatable').forEach(initDatatable);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initAll);
  } else {
    initAll();
  }
})();
</script>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aureliennicosiaulaval\.github\.io\/donnees-bleues\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Données bleues · version 0.1.0 · 23 août 2026</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/AurelienNicosiaULaval/donnees-bleues/blob/main/datasets/arbres-publics-montreal/fiche.qmd" class="toc-action"><i class="bi bi-github"></i>Voir la source</a></li><li><a href="https://github.com/AurelienNicosiaULaval/donnees-bleues/issues/new" class="toc-action"><i class="bi empty"></i>Faire part d'un problème</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Des données publiques à enseigner, avec contexte.</p>
</div>
  </div>
</footer>




</body></html>