<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Localisation des établissements d’enseignement au Québec – Données bleues</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-678eb615bd8f57929f3ad5b5079cb7e5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Localisation des établissements d’enseignement au Québec – Données bleues">
<meta property="og:site_name" content="Données bleues">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/logo-donnees-bleues.svg" alt="Logo Données bleues" class="navbar-logo light-content">
    <img src="../../assets/logo-donnees-bleues.svg" alt="Logo Données bleues" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Données bleues</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
<span class="menu-text">Accueil</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../catalogue.html">
<span class="menu-text">Explorer</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../activites.html">
<span class="menu-text">Planifier</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../sequences.html">
<span class="menu-text">Séquences</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../zero-waste.html">
<span class="menu-text">Méthode</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
<span class="menu-text">À propos</span></a>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../references.html"> <i class="bi bi-book" role="img">
</i>
<span class="menu-text">Documentation</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/AurelienNicosiaULaval/donnees-bleues"> <i class="bi bi-github" role="img">
</i>
<span class="menu-text">GitHub</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../contribuer.html">
<span class="menu-text">Contribuer</span></a>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->

<!-- main -->
<main class="content page-columns page-full column-page" id="quarto-document-content">



<section class="dataset-detail-page page-columns page-full">
<section class="dataset-teacher-hero page-columns page-full">
<div class="dataset-hero-copy">
<nav class="dataset-breadcrumb">
<a href="../../catalogue.html">Catalogue</a><span>/</span><span>Éducation et territoire</span>
</nav>
<h1>
Localisation des établissements d'enseignement au Québec
</h1>
<p class="dataset-teacher-question">
Comment cartographier une ressource scolaire sans confondre les unités statistiques?
</p>
<div class="dataset-source-strip">
<span>Source : <a href="https://www.donneesquebec.ca/recherche/dataset/localisation-des-etablissements-d-enseignement-du-reseau-scolaire-au-quebec">Données Québec / Ministère de l'Éducation et Ministère de l'Enseignement supérieur</a></span><span>Licence : Attribution (CC-BY 4.0) selon les métadonnées CKAN vérifiées le 2026-06-21</span><span>Téléchargé : 2026-06-21</span>
</div>
<div class="dataset-hero-actions">
<a class="dataset-button no-external" href="#apercu-interactif">Voir les données</a><a class="dataset-button secondary no-external" href="#activites-pedagogiques">Activités</a>
</div>
</div>
<aside class="dataset-featured-activity">
<span class="dataset-panel-label">Activité prête à lancer</span>
<h2 class="anchored">
Cartographier une ressource scolaire sans mélanger les unités
</h2>
<p>
Comment cartographier une ressource scolaire sans confondre les unités statistiques?
</p>
<div class="dataset-featured-meta">
<span>30-45 minutes</span><span>Introductif</span><span>Prête à enseigner</span>
</div>
<div class="dataset-activity-chips">
<span class="dataset-activity-chip">Exercice</span><span class="dataset-activity-chip">Exploration de données</span>
</div>
</aside>
</section>
<section class="dataset-teacher-plan">
<article>
<span class="dataset-panel-label">Pourquoi l’utiliser?</span>
<p>
Pour travailler Unité statistique, Carte de points, Données ouvertes, Filtrage à partir d’un contexte éducation et territoire lié à Québec.
</p>
<div class="dataset-chip-row">
<span class="dataset-chip">Unité statistique</span><span class="dataset-chip">Carte de points</span><span class="dataset-chip">Données ouvertes</span><span class="dataset-chip">Filtrage</span><span class="dataset-chip">cartographie</span><span class="dataset-chip">données spatiales</span>
</div>
</article>
<article>
<span class="dataset-panel-label">Ce que les étudiantes et étudiants font</span>
<ul>
<li>
Cartographier une seule ressource, puis expliquer exactement ce que chaque point représente.
</li>
<li>
Comparer les catégories de réseau sans mélanger les unités statistiques.
</li>
<li>
Évaluer l'effet des régions manquantes sur un portrait territorial.
</li>
</ul>
</article>
<article>
<span class="dataset-panel-label">À cadrer en classe</span>
<p>
Faire choisir une seule ressource avant toute carte. Le point d'apprentissage est de distinguer un établissement, un immeuble, une installation et un lien école-immeuble.
</p>
</article>
</section>
<section class="dataset-r-lab" id="apercu-interactif">
<div class="dataset-section-heading">
<span>Aperçu des données</span>
<h2 class="anchored">
Entrer par les lignes, puis poser une question
</h2>
<p>
Extrait public de la table préparée à partir de la source officielle, limité à 120 lignes pour une exploration rapide.
</p>
</div>
<div class="dataset-preview-layout">
<div class="dataset-result-card">
<div class="dataset-card-label">
Table consultable
</div>
<div id="dataset-header-result-table" class="dataset-datatable">
<div class="dataset-datatable-toolbar">
<label><span>Recherche</span><input type="search" data-dataset-search="" placeholder="Filtrer"></label><label><span>Lignes</span><select data-dataset-page-size=""><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select></label><span class="dataset-datatable-count" data-dataset-count=""></span>
</div>
<div class="dataset-result-table-wrap">
<table class="dataset-result-table">
<thead>
<tr>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="0">
source_resource<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="1">
resource_label<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="2">
network_category<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="3">
unit_kind<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="4">
source_row<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="5">
date_maj_source<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="6">
code_organisme<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="7">
code_immeuble<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="8">
code_css<span aria-hidden="true"></span>
</button>
</th>
<th>
<button type="button" class="dataset-sort-button" data-dataset-sort="9">
nom<span aria-hidden="true"></span>
</button>
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
collegial
</td>
<td>
Établissements collégiaux
</td>
<td>
Collégial
</td>
<td>
Établissement
</td>
<td>
1
</td>
<td>
</td>
<td>
20510
</td>
<td>
</td>
<td>
</td>
<td>
Conservatoire de musique de Rimouski
</td>
</tr>
<tr>
<td>
collegial
</td>
<td>
Établissements collégiaux
</td>
<td>
Collégial
</td>
<td>
Établissement
</td>
<td>
119
</td>
<td>
</td>
<td>
693703
</td>
<td>
</td>
<td>
</td>
<td>
Institut Trebas Québec inc.
</td>
</tr>
<tr>
<td>
collegial
</td>
<td>
Établissements collégiaux
</td>
<td>
Collégial
</td>
<td>
Établissement
</td>
<td>
237
</td>
<td>
</td>
<td>
915090
</td>
<td>
</td>
<td>
</td>
<td>
CÉRSÉ - Centre d'études en responsabilité sociale et écocitoyenneté
</td>
</tr>
<tr>
<td>
gouvernemental
</td>
<td>
Établissements gouvernementaux
</td>
<td>
Gouvernemental
</td>
<td>
Établissement
</td>
<td>
25
</td>
<td>
</td>
<td>
36600
</td>
<td>
</td>
<td>
</td>
<td>
Kateri School
</td>
</tr>
<tr>
<td>
prive_etablissement
</td>
<td>
Établissements privés
</td>
<td>
Privé
</td>
<td>
Établissement
</td>
<td>
104
</td>
<td>
</td>
<td>
244500
</td>
<td>
</td>
<td>
</td>
<td>
École Marie-Clarac
</td>
</tr>
<tr>
<td>
prive_etablissement
</td>
<td>
Établissements privés
</td>
<td>
Privé
</td>
<td>
Établissement
</td>
<td>
222
</td>
<td>
</td>
<td>
605500
</td>
<td>
</td>
<td>
</td>
<td>
École Montessori Magog
</td>
</tr>
<tr>
<td>
prive_installation
</td>
<td>
Installations privées
</td>
<td>
Privé
</td>
<td>
Installation
</td>
<td>
89
</td>
<td>
</td>
<td>
127501
</td>
<td>
</td>
<td>
</td>
<td>
Collège Notre-Dame-de-l'Assomption, campus français
</td>
</tr>
<tr>
<td>
prive_installation
</td>
<td>
Installations privées
</td>
<td>
Privé
</td>
<td>
Installation
</td>
<td>
207
</td>
<td>
</td>
<td>
349501
</td>
<td>
</td>
<td>
</td>
<td>
Externat Mont-Jésus-Marie
</td>
</tr>
<tr>
<td>
prive_installation
</td>
<td>
Installations privées
</td>
<td>
Privé
</td>
<td>
Installation
</td>
<td>
325
</td>
<td>
</td>
<td>
625502
</td>
<td>
</td>
<td>
</td>
<td>
École Trilingue Vision St-Jean
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
84
</td>
<td>
</td>
<td>
712002
</td>
<td>
712039
</td>
<td>
712000
</td>
<td>
École de l'Estran
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
202
</td>
<td>
</td>
<td>
714003
</td>
<td>
714084
</td>
<td>
714000
</td>
<td>
École des Vieux-Moulins et Saint-Modeste
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
320
</td>
<td>
</td>
<td>
721085
</td>
<td>
721069
</td>
<td>
721000
</td>
<td>
École secondaire des Grandes-Rivières
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
438
</td>
<td>
</td>
<td>
722461
</td>
<td>
723073
</td>
<td>
722000
</td>
<td>
Centre de formation professionnelle Alma
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
556
</td>
<td>
</td>
<td>
731003
</td>
<td>
731018
</td>
<td>
731000
</td>
<td>
École Les Marées montantes
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
674
</td>
<td>
</td>
<td>
732476
</td>
<td>
732075
</td>
<td>
732000
</td>
<td>
École hôtelière de la Capitale
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
792
</td>
<td>
</td>
<td>
734065
</td>
<td>
734065
</td>
<td>
734000
</td>
<td>
École Le Sommet
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
910
</td>
<td>
</td>
<td>
741155
</td>
<td>
741046
</td>
<td>
741000
</td>
<td>
École intégrée des Forges
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
1028
</td>
<td>
</td>
<td>
742352
</td>
<td>
742121
</td>
<td>
742000
</td>
<td>
Centre d'éducation des adultes du Saint-Maurice
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
1146
</td>
<td>
</td>
<td>
742461
</td>
<td>
742063
</td>
<td>
742000
</td>
<td>
École forestière de La Tuque - Formation professionnelle
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
1264
</td>
<td>
</td>
<td>
752021
</td>
<td>
752135
</td>
<td>
752000
</td>
<td>
École Notre-Dame-du-Rosaire
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
1382
</td>
<td>
</td>
<td>
759013
</td>
<td>
759142
</td>
<td>
759000
</td>
<td>
École Upichinaausiun Chiskutimatukimikw School
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
1500
</td>
<td>
</td>
<td>
761477
</td>
<td>
761027
</td>
<td>
761000
</td>
<td>
Centre de formation des Métiers de l'Acier
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
1618
</td>
<td>
</td>
<td>
762122
</td>
<td>
762090
</td>
<td>
762000
</td>
<td>
École Barclay
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
1736
</td>
<td>
</td>
<td>
762315
</td>
<td>
762200
</td>
<td>
762000
</td>
<td>
Centre Marie-Médiatrice
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
1854
</td>
<td>
</td>
<td>
763203
</td>
<td>
763144
</td>
<td>
763000
</td>
<td>
École Gentilly
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
1972
</td>
<td>
</td>
<td>
769102
</td>
<td>
769738
</td>
<td>
769000
</td>
<td>
École Ikaarvik
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
2090
</td>
<td>
</td>
<td>
772302
</td>
<td>
772022
</td>
<td>
772000
</td>
<td>
Centre d'éducation des adultes des Portages-de-l'Outaouais
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
2208
</td>
<td>
</td>
<td>
782007
</td>
<td>
782007
</td>
<td>
782000
</td>
<td>
École Notre-Dame-de-Protection
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
2326
</td>
<td>
</td>
<td>
784014
</td>
<td>
784850
</td>
<td>
784000
</td>
<td>
École Saint-Isidore
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
2444
</td>
<td>
</td>
<td>
792047
</td>
<td>
792047
</td>
<td>
792000
</td>
<td>
École Jean-du-Nord / Manikoutai
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
2562
</td>
<td>
</td>
<td>
812407
</td>
<td>
812001
</td>
<td>
812000
</td>
<td>
Centre de formation professionnelle de La Haute-Gaspésie
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
2680
</td>
<td>
</td>
<td>
821247
</td>
<td>
821047
</td>
<td>
821000
</td>
<td>
École secondaire Louis-Jacques-Casault
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
2798
</td>
<td>
</td>
<td>
823043
</td>
<td>
823043
</td>
<td>
823000
</td>
<td>
École des Sommets
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
2916
</td>
<td>
</td>
<td>
823361
</td>
<td>
823084
</td>
<td>
823000
</td>
<td>
Centre d'éducation des adultes Monseigneur-Beaudoin-Les Sources
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
3034
</td>
<td>
</td>
<td>
824217
</td>
<td>
824113
</td>
<td>
824000
</td>
<td>
École secondaire Champagnat, Guillaume-Couture
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
3152
</td>
<td>
</td>
<td>
831102
</td>
<td>
831018
</td>
<td>
831000
</td>
<td>
École Curé-Antoine-Labelle
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
3270
</td>
<td>
</td>
<td>
831460
</td>
<td>
831018
</td>
<td>
831000
</td>
<td>
Centre de formation horticole de Laval
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
3388
</td>
<td>
</td>
<td>
841301
</td>
<td>
841812
</td>
<td>
841000
</td>
<td>
Centre la Croisée
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
3506
</td>
<td>
</td>
<td>
842401
</td>
<td>
842097
</td>
<td>
842000
</td>
<td>
Centre multiservice des Samares
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
3624
</td>
<td>
</td>
<td>
851306
</td>
<td>
851834
</td>
<td>
851000
</td>
<td>
Centre de formation continue des Patriotes
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
3742
</td>
<td>
</td>
<td>
852401
</td>
<td>
852805
</td>
<td>
852000
</td>
<td>
Centre de formation du transport routier de Saint-Jérôme
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
3860
</td>
<td>
</td>
<td>
861007
</td>
<td>
861035
</td>
<td>
861000
</td>
<td>
École secondaire Fernand-Lefebvre - Pavillon Tournesol
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
3978
</td>
<td>
</td>
<td>
863035
</td>
<td>
863034
</td>
<td>
863000
</td>
<td>
École de Ramezay
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
4096
</td>
<td>
</td>
<td>
864278
</td>
<td>
864078
</td>
<td>
864000
</td>
<td>
École Gérard-Filion
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
4214
</td>
<td>
</td>
<td>
865210
</td>
<td>
865064
</td>
<td>
865000
</td>
<td>
École Jacques-Rocheleau-Saint-Basile
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
4332
</td>
<td>
</td>
<td>
865435
</td>
<td>
865102
</td>
<td>
865000
</td>
<td>
Centre de formation professionnelle des Patriotes
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
4450
</td>
<td>
</td>
<td>
867065
</td>
<td>
867028
</td>
<td>
867000
</td>
<td>
École Pierre-Bédard
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
4568
</td>
<td>
</td>
<td>
868028
</td>
<td>
868038
</td>
<td>
868000
</td>
<td>
École Edgar-Hébert
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
4686
</td>
<td>
</td>
<td>
871025
</td>
<td>
871005
</td>
<td>
871000
</td>
<td>
École l'Oasis
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
4804
</td>
<td>
</td>
<td>
873008
</td>
<td>
873019
</td>
<td>
873000
</td>
<td>
École Saint-Félix-de-Kingsey
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
4922
</td>
<td>
</td>
<td>
882009
</td>
<td>
882852
</td>
<td>
882000
</td>
<td>
École secondaire Evergreen
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
5040
</td>
<td>
</td>
<td>
883402
</td>
<td>
883022
</td>
<td>
883000
</td>
<td>
Centre de Formation professionnelle de Lennoxville
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
5158
</td>
<td>
</td>
<td>
884452
</td>
<td>
884016
</td>
<td>
884000
</td>
<td>
Centre d'expertise en Transport - ACCESS (CET-A)
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
5276
</td>
<td>
</td>
<td>
887026
</td>
<td>
887068
</td>
<td>
887000
</td>
<td>
École Nesbitt
</td>
</tr>
<tr>
<td>
public_ecole
</td>
<td>
Écoles publiques
</td>
<td>
Public
</td>
<td>
Lien école-immeuble
</td>
<td>
5394
</td>
<td>
</td>
<td>
888080
</td>
<td>
888012
</td>
<td>
888000
</td>
<td>
École primaire Clearpoint
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
54
</td>
<td>
</td>
<td>
</td>
<td>
689085
</td>
<td>
689000
</td>
<td>
Résidence 08A5,A6,A7
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
172
</td>
<td>
</td>
<td>
</td>
<td>
713011
</td>
<td>
713000
</td>
<td>
Oiseau Chanteur, de l'
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
290
</td>
<td>
</td>
<td>
</td>
<td>
721006
</td>
<td>
721000
</td>
<td>
Saint-Louis-de-Gonzague
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
408
</td>
<td>
</td>
<td>
</td>
<td>
723026
</td>
<td>
723000
</td>
<td>
Notre-Dame
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
526
</td>
<td>
</td>
<td>
</td>
<td>
732003
</td>
<td>
732000
</td>
<td>
Sans-Frontière
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
643
</td>
<td>
</td>
<td>
</td>
<td>
733074
</td>
<td>
733000
</td>
<td>
Pavillon Gilles-Vigneault
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
761
</td>
<td>
</td>
<td>
</td>
<td>
735028
</td>
<td>
735000
</td>
<td>
Marie-du-Saint-Sacrement
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
879
</td>
<td>
</td>
<td>
</td>
<td>
742053
</td>
<td>
742000
</td>
<td>
Jacques-Buteux
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
997
</td>
<td>
</td>
<td>
</td>
<td>
752204
</td>
<td>
752000
</td>
<td>
Le Ber, pavillon
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
1115
</td>
<td>
</td>
<td>
</td>
<td>
759062
</td>
<td>
759000
</td>
<td>
Bungalow
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
1233
</td>
<td>
</td>
<td>
</td>
<td>
759515
</td>
<td>
759000
</td>
<td>
Jumelé
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
1351
</td>
<td>
</td>
<td>
</td>
<td>
761007
</td>
<td>
761000
</td>
<td>
Pie-XII
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
1469
</td>
<td>
</td>
<td>
</td>
<td>
762046
</td>
<td>
762000
</td>
<td>
Saint-Léon-de-Westmount
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
1587
</td>
<td>
</td>
<td>
</td>
<td>
762209
</td>
<td>
762000
</td>
<td>
Boucher-De La Bruère
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
1705
</td>
<td>
</td>
<td>
</td>
<td>
762827
</td>
<td>
762000
</td>
<td>
Sophie-Barat, annexe temporaire
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
1823
</td>
<td>
</td>
<td>
</td>
<td>
763104
</td>
<td>
763000
</td>
<td>
Enfants-du-Monde
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
1941
</td>
<td>
</td>
<td>
</td>
<td>
769152
</td>
<td>
769000
</td>
<td>
Duplex
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
2059
</td>
<td>
</td>
<td>
</td>
<td>
769518
</td>
<td>
769000
</td>
<td>
Quadruplex
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
2177
</td>
<td>
</td>
<td>
</td>
<td>
771089
</td>
<td>
771000
</td>
<td>
Odyssée (édifice Jean XXIII), de l'
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
2295
</td>
<td>
</td>
<td>
</td>
<td>
774004
</td>
<td>
774000
</td>
<td>
Sainte-Anne, no 1
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
2413
</td>
<td>
</td>
<td>
</td>
<td>
783807
</td>
<td>
783000
</td>
<td>
La Passerelle (Saint-Félix-de-Dalquier)
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
2531
</td>
<td>
</td>
<td>
</td>
<td>
792070
</td>
<td>
792000
</td>
<td>
Maison (21, rue Brouage)
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
2649
</td>
<td>
</td>
<td>
</td>
<td>
813019
</td>
<td>
813000
</td>
<td>
Polyvalente Paspébiac et La Source
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
2767
</td>
<td>
</td>
<td>
</td>
<td>
823009
</td>
<td>
823000
</td>
<td>
Sainte-Famille
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
2885
</td>
<td>
</td>
<td>
</td>
<td>
824027
</td>
<td>
824000
</td>
<td>
Charles-Rodrigue
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
3003
</td>
<td>
</td>
<td>
</td>
<td>
831067
</td>
<td>
831000
</td>
<td>
Boisé, du
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
3121
</td>
<td>
</td>
<td>
</td>
<td>
841106
</td>
<td>
841000
</td>
<td>
Saint-Joachim
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
3239
</td>
<td>
</td>
<td>
</td>
<td>
842095
</td>
<td>
842000
</td>
<td>
Récolte, de la
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
3357
</td>
<td>
</td>
<td>
</td>
<td>
851087
</td>
<td>
851000
</td>
<td>
Perséides, des
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
3475
</td>
<td>
</td>
<td>
</td>
<td>
852808
</td>
<td>
852000
</td>
<td>
Local satellite CFTR (Joliette)
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
3593
</td>
<td>
</td>
<td>
</td>
<td>
854058
</td>
<td>
854000
</td>
<td>
Sacré-Coeur (Ferme-Neuve), du
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
3711
</td>
<td>
</td>
<td>
</td>
<td>
863025
</td>
<td>
863000
</td>
<td>
Capitaine-Luc-Fortin, Édifice Henryville
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
3829
</td>
<td>
</td>
<td>
</td>
<td>
864086
</td>
<td>
864000
</td>
<td>
Greenfield Park, du vieux
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
3947
</td>
<td>
</td>
<td>
</td>
<td>
866019
</td>
<td>
866000
</td>
<td>
Sainte-Famille
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
4065
</td>
<td>
</td>
<td>
</td>
<td>
868011
</td>
<td>
868000
</td>
<td>
Omer-Séguin
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
4183
</td>
<td>
</td>
<td>
</td>
<td>
871029
</td>
<td>
871000
</td>
<td>
Jeunesse, la
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
4301
</td>
<td>
</td>
<td>
</td>
<td>
873044
</td>
<td>
873000
</td>
<td>
Jean-Raimbault
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
4419
</td>
<td>
</td>
<td>
</td>
<td>
883950
</td>
<td>
883000
</td>
<td>
Terrain - Lot 1 140 816 - Stationnement
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
4537
</td>
<td>
</td>
<td>
</td>
<td>
886004
</td>
<td>
886000
</td>
<td>
Namur
</td>
</tr>
<tr>
<td>
public_immeuble
</td>
<td>
Immeubles publics
</td>
<td>
Public
</td>
<td>
Immeuble
</td>
<td>
4655
</td>
<td>
</td>
<td>
</td>
<td>
887962
</td>
<td>
887000
</td>
<td>
Terrains vacants - Lots 5 035 931 et 5 035 932
</td>
</tr>
<tr>
<td>
ssocial_cs
</td>
<td>
Sièges sociaux CSS et CS
</td>
<td>
Public
</td>
<td>
Siège social CSS ou CS
</td>
<td>
42
</td>
<td>
</td>
<td>
822000
</td>
<td>
</td>
<td>
</td>
<td>
Centre de services scolaire des Appalaches
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
88
</td>
<td>
</td>
<td>
713009
</td>
<td>
</td>
<td>
</td>
<td>
École de Saint-Jean-de-Dieu
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
206
</td>
<td>
</td>
<td>
724014
</td>
<td>
</td>
<td>
</td>
<td>
École polyvalente Jonquière
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
324
</td>
<td>
</td>
<td>
733390
</td>
<td>
</td>
<td>
</td>
<td>
Centre d'éducation des adultes Le Phénix
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
442
</td>
<td>
</td>
<td>
741403
</td>
<td>
</td>
<td>
</td>
<td>
Centre de formation professionnelle Qualitech
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
560
</td>
<td>
</td>
<td>
752155
</td>
<td>
</td>
<td>
</td>
<td>
École Le Monarque
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
678
</td>
<td>
</td>
<td>
761370
</td>
<td>
</td>
<td>
</td>
<td>
Centre d'éducation aux adultes Daniel-Johnson
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
796
</td>
<td>
</td>
<td>
762149
</td>
<td>
</td>
<td>
</td>
<td>
École Saint-Pascal-Baylon
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
914
</td>
<td>
</td>
<td>
763109
</td>
<td>
</td>
<td>
</td>
<td>
École Martin-Bélanger
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
1032
</td>
<td>
</td>
<td>
771052
</td>
<td>
</td>
<td>
</td>
<td>
École des Belles-Rives
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
1150
</td>
<td>
</td>
<td>
783020
</td>
<td>
</td>
<td>
</td>
<td>
École Notre-Dame-de-Fatima
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
1268
</td>
<td>
</td>
<td>
812021
</td>
<td>
</td>
<td>
</td>
<td>
École des Prospecteurs
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
1386
</td>
<td>
</td>
<td>
822045
</td>
<td>
</td>
<td>
</td>
<td>
Polyvalente de Thetford Mines
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
1504
</td>
<td>
</td>
<td>
831009
</td>
<td>
</td>
<td>
</td>
<td>
École Des Cèdres
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
1622
</td>
<td>
</td>
<td>
841049
</td>
<td>
</td>
<td>
</td>
<td>
École au Point-du-Jour
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
1740
</td>
<td>
</td>
<td>
851171
</td>
<td>
</td>
<td>
</td>
<td>
École secondaire Jean-Jacques-Rousseau
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
1858
</td>
<td>
</td>
<td>
852049
</td>
<td>
</td>
<td>
</td>
<td>
École de l'Étincelle
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
1976
</td>
<td>
</td>
<td>
863022
</td>
<td>
</td>
<td>
</td>
<td>
École Hamel
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
2094
</td>
<td>
</td>
<td>
865107
</td>
<td>
</td>
<td>
</td>
<td>
École Le Tournesol
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
2212
</td>
<td>
</td>
<td>
867007
</td>
<td>
</td>
<td>
</td>
<td>
École de la Magdeleine
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
2330
</td>
<td>
</td>
<td>
869053
</td>
<td>
</td>
<td>
</td>
<td>
École secondaire des Échos
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
2448
</td>
<td>
</td>
<td>
881004
</td>
<td>
</td>
<td>
</td>
<td>
École primaire Holland
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
2566
</td>
<td>
</td>
<td>
885168
</td>
<td>
</td>
<td>
</td>
<td>
École primaire Saint-Jude
</td>
</tr>
<tr>
<td>
ssocial_org
</td>
<td>
Sièges sociaux organismes
</td>
<td>
Public
</td>
<td>
Siège social organisme
</td>
<td>
2684
</td>
<td>
</td>
<td>
887254
</td>
<td>
</td>
<td>
</td>
<td>
Hôpital de Montréal pour enfants
</td>
</tr>
<tr>
<td>
universitaire
</td>
<td>
Établissements universitaires
</td>
<td>
Universitaire
</td>
<td>
Établissement
</td>
<td>
24
</td>
<td>
</td>
<td>
989000
</td>
<td>
</td>
<td>
</td>
<td>
Collège militaire royal de Saint-Jean
</td>
</tr>
</tbody>
</table>
</div>
<div class="dataset-datatable-pager">
<button type="button" data-dataset-prev="">
Précédent
</button>
<span data-dataset-page=""></span><button type="button" data-dataset-next="">Suivant</button>
</div>
</div>
<div class="dataset-preview-chart">
<span class="dataset-panel-label">Aperçu graphique</span><svg class="dataset-r-chart" viewbox="0 0 320 210" role="img" aria-label="Aperçu numérique généré par R"><line x1="34" y1="158" x2="292" y2="158" class="dataset-svg-axis"></line><line x1="34" y1="36" x2="34" y2="158" class="dataset-svg-axis"></line><polyline points="34,86 40.4,83.1 46.7,80.2 53.1,77.4 59.4,74.5 65.8,71.7 72.2,68.8 78.5,66 84.9,63.1 91.2,60.3 97.6,57.4 103.9,54.6 110.3,51.7 116.7,48.9 123,46 129.4,157.6 135.7,156.5 142.1,153.6 148.5,150.7 154.8,147.9 161.2,145 167.5,142.2 173.9,139.3 180.3,136.5 186.6,133.6 193,130.8 199.3,127.9 205.7,125.1 212.1,122.2 218.4,119.4 224.8,116.5 231.1,113.6 237.5,110.8 243.8,107.9 250.2,105.1 256.6,102.2 262.9,99.4 269.3,96.5 275.6,93.7 282,158" class="dataset-svg-line"></polyline><circle cx="34" cy="86" r="3.2" class="dataset-svg-point"></circle><circle cx="40.4" cy="83.1" r="3.2" class="dataset-svg-point"></circle><circle cx="46.7" cy="80.2" r="3.2" class="dataset-svg-point"></circle><circle cx="53.1" cy="77.4" r="3.2" class="dataset-svg-point"></circle><circle cx="59.4" cy="74.5" r="3.2" class="dataset-svg-point"></circle><circle cx="65.8" cy="71.7" r="3.2" class="dataset-svg-point"></circle><circle cx="72.2" cy="68.8" r="3.2" class="dataset-svg-point"></circle><circle cx="78.5" cy="66" r="3.2" class="dataset-svg-point"></circle><circle cx="84.9" cy="63.1" r="3.2" class="dataset-svg-point"></circle><circle cx="91.2" cy="60.3" r="3.2" class="dataset-svg-point"></circle><circle cx="97.6" cy="57.4" r="3.2" class="dataset-svg-point"></circle><circle cx="103.9" cy="54.6" r="3.2" class="dataset-svg-point"></circle><circle cx="110.3" cy="51.7" r="3.2" class="dataset-svg-point"></circle><circle cx="116.7" cy="48.9" r="3.2" class="dataset-svg-point"></circle><circle cx="123" cy="46" r="3.2" class="dataset-svg-point"></circle><circle cx="129.4" cy="157.6" r="3.2" class="dataset-svg-point"></circle><circle cx="135.7" cy="156.5" r="3.2" class="dataset-svg-point"></circle><circle cx="142.1" cy="153.6" r="3.2" class="dataset-svg-point"></circle><circle cx="148.5" cy="150.7" r="3.2" class="dataset-svg-point"></circle><circle cx="154.8" cy="147.9" r="3.2" class="dataset-svg-point"></circle><circle cx="161.2" cy="145" r="3.2" class="dataset-svg-point"></circle><circle cx="167.5" cy="142.2" r="3.2" class="dataset-svg-point"></circle><circle cx="173.9" cy="139.3" r="3.2" class="dataset-svg-point"></circle><circle cx="180.3" cy="136.5" r="3.2" class="dataset-svg-point"></circle><circle cx="186.6" cy="133.6" r="3.2" class="dataset-svg-point"></circle><circle cx="193" cy="130.8" r="3.2" class="dataset-svg-point"></circle><circle cx="199.3" cy="127.9" r="3.2" class="dataset-svg-point"></circle><circle cx="205.7" cy="125.1" r="3.2" class="dataset-svg-point"></circle><circle cx="212.1" cy="122.2" r="3.2" class="dataset-svg-point"></circle><circle cx="218.4" cy="119.4" r="3.2" class="dataset-svg-point"></circle><circle cx="224.8" cy="116.5" r="3.2" class="dataset-svg-point"></circle><circle cx="231.1" cy="113.6" r="3.2" class="dataset-svg-point"></circle><circle cx="237.5" cy="110.8" r="3.2" class="dataset-svg-point"></circle><circle cx="243.8" cy="107.9" r="3.2" class="dataset-svg-point"></circle><circle cx="250.2" cy="105.1" r="3.2" class="dataset-svg-point"></circle><circle cx="256.6" cy="102.2" r="3.2" class="dataset-svg-point"></circle><circle cx="262.9" cy="99.4" r="3.2" class="dataset-svg-point"></circle><circle cx="269.3" cy="96.5" r="3.2" class="dataset-svg-point"></circle><circle cx="275.6" cy="93.7" r="3.2" class="dataset-svg-point"></circle><circle cx="282" cy="158" r="3.2" class="dataset-svg-point"></circle><text x="34" y="24" class="dataset-svg-title">source_row</text><text x="34" y="186" class="dataset-svg-label">24</text><text x="230" y="186" class="dataset-svg-label">4655</text><text x="34" y="202" class="dataset-svg-label">1</text><text x="250" y="202" class="dataset-svg-label">40</text></svg>
</div>
</div>
<div class="dataset-variable-panel">
<span class="dataset-panel-label">Variables à repérer</span>
<div class="dataset-variable-list">
<span class="dataset-variable-chip">source_resource</span><span class="dataset-variable-chip">resource_label</span><span class="dataset-variable-chip">network_category</span><span class="dataset-variable-chip">unit_kind</span><span class="dataset-variable-chip">source_row</span><span class="dataset-variable-chip">date_maj_source</span><span class="dataset-variable-chip">code_organisme</span>
</div>
<div class="dataset-simple-facts">
<div class="dataset-simple-fact">
<span>Territoire</span><strong>Québec</strong>
</div>
<div class="dataset-simple-fact">
<span>Niveau</span><strong>Introduction à intermédiaire</strong>
</div>
<div class="dataset-simple-fact">
<span>Format</span><strong>9 CSV officiels préparés localement en table longue harmonisée</strong>
</div>
</div>
</div>
</div>
</section>
<details class="dataset-doc-panel" id="documentation">
<summary>
<span>Documentation complète</span><strong>Sources, variables, code R minimal, méthode et limites</strong>
</summary>
<div class="dataset-detail-content">
<section id="pourquoi-ce-jeu-est-intéressant" class="level2">
<h2 class="anchored" data-anchor-id="pourquoi-ce-jeu-est-intéressant">Pourquoi ce jeu est intéressant</h2>
<p>Ce jeu est utile parce qu’il force une décision statistique simple, mais essentielle : avant de compter, il faut savoir ce qu’une ligne représente. La source regroupe des établissements, des installations, des liens école-immeuble, des immeubles et des sièges sociaux. Une analyse correcte commence donc par le choix explicite de la ressource et de l’unité statistique.</p>
<p>Il se prête bien à un cours d’introduction en science des données : importation de données ouvertes, harmonisation de fichiers, variables catégorielles, coordonnées géographiques, tableaux de fréquences, cartes et limites d’interprétation.</p>
</section>
<section id="ce-qui-a-été-vérifié" class="level2">
<h2 class="anchored" data-anchor-id="ce-qui-a-été-vérifié">Ce qui a été vérifié</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Élément</th>
<th>Résultat vérifié</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Paquet CKAN</td>
<td><code>2d3b5cf8-b347-49c7-ad3b-bd6a9c15e443</code></td>
</tr>
<tr class="even">
<td>Source officielle</td>
<td>Données Québec, Ministère de l’Éducation et Ministère de l’Enseignement supérieur</td>
</tr>
<tr class="odd">
<td>Ressources dans le paquet</td>
<td>28 ressources</td>
</tr>
<tr class="even">
<td>Ressources CSV préparées ici</td>
<td>9 ressources</td>
</tr>
<tr class="odd">
<td>Licence</td>
<td>Attribution (CC-BY 4.0), selon les métadonnées CKAN consultées le 2026-06-21</td>
</tr>
<tr class="even">
<td>Dernière modification du paquet CKAN</td>
<td>2026-06-16</td>
</tr>
<tr class="odd">
<td>Table préparée</td>
<td><code>data/processed/etablissements-enseignement/etablissements_enseignement_quebec.csv</code></td>
</tr>
<tr class="even">
<td>Résumé des ressources</td>
<td><code>data/processed/etablissements-enseignement/ressources_etablissements_enseignement.csv</code></td>
</tr>
</tbody>
</table>
</section>
<section id="source-et-conditions" class="level2">
<h2 class="anchored" data-anchor-id="source-et-conditions">Source et conditions</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Champ</th>
<th>Information</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Page Données Québec</td>
<td><a href="https://www.donneesquebec.ca/recherche/dataset/localisation-des-etablissements-d-enseignement-du-reseau-scolaire-au-quebec" class="uri">https://www.donneesquebec.ca/recherche/dataset/localisation-des-etablissements-d-enseignement-du-reseau-scolaire-au-quebec</a></td>
</tr>
<tr class="even">
<td>API CKAN</td>
<td><a href="https://www.donneesquebec.ca/recherche/api/3/action/package_show?id=localisation-des-etablissements-d-enseignement-du-reseau-scolaire-au-quebec" class="uri">https://www.donneesquebec.ca/recherche/api/3/action/package_show?id=localisation-des-etablissements-d-enseignement-du-reseau-scolaire-au-quebec</a></td>
</tr>
<tr class="odd">
<td>Page Québec.ca</td>
<td><a href="https://www.quebec.ca/education/cartes-donnees-geographiques" class="uri">https://www.quebec.ca/education/cartes-donnees-geographiques</a></td>
</tr>
<tr class="even">
<td>Miroir ouvert.canada.ca</td>
<td><a href="https://open.canada.ca/data/fr/dataset/2d3b5cf8-b347-49c7-ad3b-bd6a9c15e443" class="uri">https://open.canada.ca/data/fr/dataset/2d3b5cf8-b347-49c7-ad3b-bd6a9c15e443</a></td>
</tr>
<tr class="odd">
<td>Territoire</td>
<td>Québec</td>
</tr>
<tr class="even">
<td>Date d’accès</td>
<td>2026-06-21</td>
</tr>
<tr class="odd">
<td>Redistribution pédagogique</td>
<td>Possible sous réserve du respect de la licence Attribution (CC-BY 4.0)</td>
</tr>
</tbody>
</table>
</section>
<section id="ce-que-représente-une-ligne" class="level2">
<h2 class="anchored" data-anchor-id="ce-que-représente-une-ligne">Ce que représente une ligne</h2>
<p>La table préparée contient une ligne pour chaque ligne source conservée dans l’une des 9 ressources CSV. Ce n’est pas une table de personnes, ni une table d’élèves, ni une table unique d’établissements scolaires.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Rôle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>source_resource</code></td>
<td>Identifiant court de la ressource d’origine</td>
</tr>
<tr class="even">
<td><code>resource_label</code></td>
<td>Nom lisible de la ressource d’origine</td>
</tr>
<tr class="odd">
<td><code>network_category</code></td>
<td>Catégorie de réseau : public, privé, collégial, universitaire ou gouvernemental</td>
</tr>
<tr class="even">
<td><code>unit_kind</code></td>
<td>Unité statistique de la ligne</td>
</tr>
<tr class="odd">
<td><code>source_row</code></td>
<td>Numéro de ligne dans le fichier source</td>
</tr>
</tbody>
</table>
<p>Cette distinction est le coeur pédagogique de la fiche. Par exemple, une ligne de <code>public_ecole</code> correspond à un lien école-immeuble, tandis qu’une ligne de <code>public_immeuble</code> correspond à un immeuble. Les deux fichiers peuvent être utiles, mais ils ne répondent pas à la même question statistique.</p>
</section>
<section id="variables-principales" class="level2">
<h2 class="anchored" data-anchor-id="variables-principales">Variables principales</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable préparée</th>
<th>Utilisation</th>
<th>Point de vigilance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>nom</code></td>
<td>Nom principal harmonisé</td>
<td>Peut provenir du nom de l’organisme ou de l’immeuble</td>
</tr>
<tr class="even">
<td><code>nom_organisme</code></td>
<td>Nom de l’organisme</td>
<td>Disponible selon la ressource</td>
</tr>
<tr class="odd">
<td><code>nom_immeuble</code></td>
<td>Nom de l’immeuble</td>
<td>Disponible surtout pour les ressources liées aux immeubles</td>
</tr>
<tr class="even">
<td><code>municipalite</code></td>
<td>Regroupement municipal</td>
<td>Les noms doivent être traités comme des libellés sources</td>
</tr>
<tr class="odd">
<td><code>mrc</code></td>
<td>Regroupement territorial</td>
<td>Variable incomplète selon les ressources</td>
</tr>
<tr class="even">
<td><code>region_administrative</code></td>
<td>Comparaison régionale</td>
<td>7 847 lignes préparées n’ont pas de région administrative</td>
</tr>
<tr class="odd">
<td><code>ordre_enseignement</code></td>
<td>Ordre ou combinaison d’ordres</td>
<td>Variable absente pour certaines unités</td>
</tr>
<tr class="even">
<td><code>longitude</code>, <code>latitude</code></td>
<td>Cartographie ponctuelle</td>
<td>Toutes les lignes préparées ont des coordonnées</td>
</tr>
<tr class="odd">
<td><code>has_coordinates</code></td>
<td>Indicateur de coordonnées complètes</td>
<td>Vaut vrai pour les 14 067 lignes préparées</td>
</tr>
<tr class="even">
<td><code>has_region</code></td>
<td>Indicateur de région non manquante</td>
<td>À utiliser avant une analyse régionale</td>
</tr>
</tbody>
</table>
</section>
<section id="taille-et-structure" class="level2">
<h2 class="anchored" data-anchor-id="taille-et-structure">Taille et structure</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Indicateur</th>
<th style="text-align: right;">Valeur</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lignes préparées</td>
<td style="text-align: right;">14 067</td>
</tr>
<tr class="even">
<td>Colonnes préparées</td>
<td style="text-align: right;">31</td>
</tr>
<tr class="odd">
<td>Ressources CSV retenues</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td>Lignes avec coordonnées</td>
<td style="text-align: right;">14 067</td>
</tr>
<tr class="odd">
<td>Lignes avec région administrative</td>
<td style="text-align: right;">6 220</td>
</tr>
<tr class="even">
<td>Lignes sans région administrative</td>
<td style="text-align: right;">7 847</td>
</tr>
<tr class="odd">
<td>Catégories de réseau</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
</section>
<section id="ressources-retenues" class="level2">
<h2 class="anchored" data-anchor-id="ressources-retenues">Ressources retenues</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ressource</th>
<th>Unité statistique</th>
<th style="text-align: right;">Lignes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Écoles publiques</td>
<td>Lien école-immeuble</td>
<td style="text-align: right;">5 466</td>
</tr>
<tr class="even">
<td>Immeubles publics</td>
<td>Immeuble</td>
<td style="text-align: right;">4 740</td>
</tr>
<tr class="odd">
<td>Sièges sociaux organismes</td>
<td>Siège social organisme</td>
<td style="text-align: right;">2 779</td>
</tr>
<tr class="even">
<td>Installations privées</td>
<td>Installation</td>
<td style="text-align: right;">361</td>
</tr>
<tr class="odd">
<td>Établissements collégiaux</td>
<td>Établissement</td>
<td style="text-align: right;">330</td>
</tr>
<tr class="even">
<td>Établissements privés</td>
<td>Établissement</td>
<td style="text-align: right;">256</td>
</tr>
<tr class="odd">
<td>Sièges sociaux CSS et CS</td>
<td>Siège social CSS ou CS</td>
<td style="text-align: right;">72</td>
</tr>
<tr class="even">
<td>Établissements gouvernementaux</td>
<td>Établissement</td>
<td style="text-align: right;">39</td>
</tr>
<tr class="odd">
<td>Établissements universitaires</td>
<td>Établissement</td>
<td style="text-align: right;">24</td>
</tr>
</tbody>
</table>
</section>
<section id="catégories-de-réseau" class="level2">
<h2 class="anchored" data-anchor-id="catégories-de-réseau">Catégories de réseau</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Catégorie</th>
<th style="text-align: right;">Lignes préparées</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Public</td>
<td style="text-align: right;">13 057</td>
</tr>
<tr class="even">
<td>Privé</td>
<td style="text-align: right;">617</td>
</tr>
<tr class="odd">
<td>Collégial</td>
<td style="text-align: right;">330</td>
</tr>
<tr class="even">
<td>Gouvernemental</td>
<td style="text-align: right;">39</td>
</tr>
<tr class="odd">
<td>Universitaire</td>
<td style="text-align: right;">24</td>
</tr>
</tbody>
</table>
<p>Le poids du réseau public dans cette table ne signifie pas que le réseau public compte simplement 13 057 établissements. Il reflète surtout le fait que plusieurs ressources publiques distinctes sont incluses.</p>
</section>
<section id="régions-les-plus-représentées" class="level2">
<h2 class="anchored" data-anchor-id="régions-les-plus-représentées">Régions les plus représentées</h2>
<p>Ce tableau utilise seulement les 6 220 lignes où <code>region_administrative</code> est renseignée.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Région administrative</th>
<th style="text-align: right;">Lignes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Montréal</td>
<td style="text-align: right;">1 024</td>
</tr>
<tr class="even">
<td>Montérégie</td>
<td style="text-align: right;">991</td>
</tr>
<tr class="odd">
<td>Chaudière-Appalaches</td>
<td style="text-align: right;">460</td>
</tr>
<tr class="even">
<td>Estrie</td>
<td style="text-align: right;">392</td>
</tr>
<tr class="odd">
<td>Laurentides</td>
<td style="text-align: right;">372</td>
</tr>
<tr class="even">
<td>Capitale-Nationale</td>
<td style="text-align: right;">369</td>
</tr>
<tr class="odd">
<td>Mauricie</td>
<td style="text-align: right;">366</td>
</tr>
</tbody>
</table>
<p>Ce n’est pas une mesure directe d’accessibilité scolaire. Pour parler d’accès, il faudrait ajouter au minimum des données de population, de distance, de transport ou de bassin de desserte.</p>
</section>
<section id="lecture-statistique" class="level2">
<h2 class="anchored" data-anchor-id="lecture-statistique">Lecture statistique</h2>
<p>L’analyse recommandée commence par trois filtres.</p>
<ol type="1">
<li>Choisir une ressource avec <code>source_resource</code>.</li>
<li>Vérifier l’unité statistique avec <code>unit_kind</code>.</li>
<li>Utiliser <code>has_region</code> ou <code>has_coordinates</code> selon la question.</li>
</ol>
<p>Un exemple valide : cartographier les <code>Écoles publiques</code> et expliquer que chaque point représente un lien école-immeuble. Un exemple fragile : additionner directement les 9 ressources pour dire combien il existe d’établissements au Québec. Ce deuxième calcul mélange plusieurs unités statistiques et peut compter des objets institutionnels liés entre eux.</p>
</section>
<section id="concepts-enseignables" class="level2">
<h2 class="anchored" data-anchor-id="concepts-enseignables">Concepts enseignables</h2>
<ul>
<li>unité statistique</li>
<li>source multi-ressources</li>
<li>données spatiales ponctuelles</li>
<li>variables catégorielles</li>
<li>données manquantes</li>
<li>tableau de fréquences</li>
<li>carte exploratoire</li>
<li>limites d’interprétation</li>
</ul>
</section>
<section id="score-zéro-déchet" class="level2">
<h2 class="anchored" data-anchor-id="score-zéro-déchet">Score zéro déchet</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th style="text-align: right;">Score</th>
<th>Justification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Contexte québécois</td>
<td style="text-align: right;">3</td>
<td>Données officielles sur le réseau d’enseignement du Québec</td>
</tr>
<tr class="even">
<td>Accessibilité pédagogique</td>
<td style="text-align: right;">3</td>
<td>Variables concrètes : noms, régions, ordres, coordonnées</td>
</tr>
<tr class="odd">
<td>Qualité documentaire</td>
<td style="text-align: right;">3</td>
<td>Source officielle, API CKAN et documentation cartographique</td>
</tr>
<tr class="even">
<td>Potentiel de nettoyage</td>
<td style="text-align: right;">3</td>
<td>Harmonisation nécessaire de 9 ressources</td>
</tr>
<tr class="odd">
<td>Potentiel de visualisation</td>
<td style="text-align: right;">3</td>
<td>Cartes et comparaisons régionales naturelles</td>
</tr>
<tr class="even">
<td>Potentiel de statistique descriptive</td>
<td style="text-align: right;">3</td>
<td>Fréquences, regroupements, proportions et données manquantes</td>
</tr>
<tr class="odd">
<td>Potentiel d’inférence</td>
<td style="text-align: right;">1</td>
<td>Peu adapté à l’inférence sans données complémentaires</td>
</tr>
<tr class="even">
<td>Potentiel de modélisation</td>
<td style="text-align: right;">2</td>
<td>Modélisation possible après ajout de population ou de distances</td>
</tr>
<tr class="odd">
<td>Potentiel éthique</td>
<td style="text-align: right;">3</td>
<td>Discussion sur accès territorial, interprétation publique et limites</td>
</tr>
<tr class="even">
<td>Réutilisabilité</td>
<td style="text-align: right;">3</td>
<td>Pertinent en importation, visualisation, nettoyage et communication</td>
</tr>
</tbody>
</table>
<p>Total : 27 sur 30.</p>
</section>
<section id="activité-courte" class="level2">
<h2 class="anchored" data-anchor-id="activité-courte">Activité courte</h2>
<p>En 30 à 45 minutes, choisir une seule ressource, tracer les points et rédiger une phrase qui décrit précisément l’unité statistique utilisée.</p>
</section>
<section id="activité-longue" class="level2">
<h2 class="anchored" data-anchor-id="activité-longue">Activité longue</h2>
<p>En 2 à 3 heures, produire un portrait territorial prudent : carte, tableau par réseau, analyse des régions manquantes et limites sur l’accessibilité.</p>
</section>
<section id="code-r-minimal" class="level2">
<h2 class="anchored" data-anchor-id="code-r-minimal">Code R minimal</h2>
<p>À exécuter depuis la racine du projet.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare official CSV resources</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"datasets/etablissements-enseignement/preparation.R"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Import prepared table</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>etablissements <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/processed/etablissements-enseignement/etablissements_enseignement_quebec.csv"</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Check units before counting</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>etablissements <span class="sc">|&gt;</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(source_resource, resource_label, unit_kind, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Map one coherent resource</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>ecoles_publiques <span class="ot">&lt;-</span> etablissements <span class="sc">|&gt;</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(source_resource <span class="sc">==</span> <span class="st">"public_ecole"</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ecoles_publiques, <span class="fu">aes</span>(<span class="at">x =</span> longitude, <span class="at">y =</span> latitude)) <span class="sc">+</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.35</span>, <span class="at">size =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_quickmap</span>() <span class="sc">+</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Longitude"</span>,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Latitude"</span>,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Écoles publiques du Québec"</span>,</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Chaque point représente un lien école-immeuble dans la ressource source"</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="limites-et-précautions" class="level2">
<h2 class="anchored" data-anchor-id="limites-et-précautions">Limites et précautions</h2>
<ul>
<li>Les 9 ressources ne doivent pas être additionnées sans réflexion sur l’unité statistique.</li>
<li>Une coordonnée ne mesure pas l’accessibilité réelle d’un service.</li>
<li>Les 7 847 lignes sans région administrative peuvent biaiser une comparaison régionale si elles sont exclues sans justification.</li>
<li>Les noms, municipalités et régions sont traités comme des libellés sources, pas comme des identifiants administratifs normalisés.</li>
<li>Pour étudier l’accès scolaire, il faut joindre d’autres données : population, distance, transport, capacité ou effectifs.</li>
</ul>
</section>
<section id="extensions" class="level2">
<h2 class="anchored" data-anchor-id="extensions">Extensions</h2>
<ul>
<li>Transformer les coordonnées en objets <code>sf</code>.</li>
<li>Comparer les cartes obtenues avec <code>public_ecole</code> et <code>public_immeuble</code>.</li>
<li>Calculer la proportion de lignes sans région par ressource.</li>
<li>Joindre des données démographiques régionales.</li>
<li>Construire un court rapport sur les risques d’interprétation d’un comptage naïf.</li>
</ul>
</section>
<section id="références-utilisées" class="level2">
<h2 class="anchored" data-anchor-id="références-utilisées">Références utilisées</h2>
<ul>
<li>Données Québec. 2026. Localisation des établissements d’enseignement du réseau scolaire au Québec. <a href="https://www.donneesquebec.ca/recherche/dataset/localisation-des-etablissements-d-enseignement-du-reseau-scolaire-au-quebec" class="uri">https://www.donneesquebec.ca/recherche/dataset/localisation-des-etablissements-d-enseignement-du-reseau-scolaire-au-quebec</a></li>
<li>Gouvernement du Québec. 2025. Consulter les cartes et les données géographiques en lien avec l’éducation. <a href="https://www.quebec.ca/education/cartes-donnees-geographiques" class="uri">https://www.quebec.ca/education/cartes-donnees-geographiques</a></li>
<li>Gouvernement du Canada. 2026. Localisation des établissements d’enseignement du réseau scolaire au Québec, miroir ouvert.canada.ca. <a href="https://open.canada.ca/data/fr/dataset/2d3b5cf8-b347-49c7-ad3b-bd6a9c15e443" class="uri">https://open.canada.ca/data/fr/dataset/2d3b5cf8-b347-49c7-ad3b-bd6a9c15e443</a></li>
</ul>
</section>
</div>
</details>
<section class="dataset-activities-panel" id="activites-pedagogiques">
<div class="dataset-section-heading">
<span>Activités pédagogiques</span>
<h2 class="anchored">
Pour aller plus loin
</h2>
</div>
<div class="dataset-activity-grid">
<a class="dataset-activity-card" href="activite-courte.html">
<div class="dataset-activity-meta">
<span>30-45 minutes</span><span>Introductif</span><span class="dataset-activity-status">Prête à enseigner</span>
</div>
<strong>Cartographier une ressource scolaire sans mélanger les unités</strong>
<p>
Comment cartographier une ressource scolaire sans confondre les unités statistiques?
</p>
<div class="dataset-activity-chips">
<span class="dataset-activity-chip">Exercice</span><span class="dataset-activity-chip">Exploration de données</span>
</div>
<p class="dataset-activity-output">
À produire : Une carte ou un graphique descriptif accompagné d'une phrase sur l'unité statistique et les limites.
</p>
</a> <a class="dataset-activity-card" href="activite-longue.html">
<div class="dataset-activity-meta">
<span>2-3 heures</span><span>Intermédiaire</span><span class="dataset-activity-status">Prête à enseigner</span>
</div>
<strong>Portrait territorial prudent des établissements d'enseignement</strong>
<p>
Comment décrire un territoire scolaire sans surinterpréter une source de localisation?
</p>
<div class="dataset-activity-chips">
<span class="dataset-activity-chip">Projet ou tâche longue</span><span class="dataset-activity-chip">Étude de cas</span>
</div>
<p class="dataset-activity-output">
À produire : Un court rapport reproductible avec contexte, tableau ou graphique, interprétation et limites.
</p>
</a>
</div>
</section>
</section>
<script>
(function() {
  function normalize(value) {
    return (value || '').toString().toLocaleLowerCase('fr-CA');
  }
  function numericValue(value) {
    var cleaned = (value || '').toString().replace(/\s/g, '').replace(',', '.');
    if (!/^[-+]?\d*(\.\d+)?$/.test(cleaned) || cleaned === '' || cleaned === '-' || cleaned === '+') {
      return null;
    }
    var parsed = Number(cleaned);
    return Number.isFinite(parsed) ? parsed : null;
  }
  function initDatatable(root) {
    if (root.dataset.enhanced === 'true') return;
    root.dataset.enhanced = 'true';
    var table = root.querySelector('table');
    var tbody = root.querySelector('tbody');
    if (!table || !tbody) return;
    var rows = Array.from(tbody.querySelectorAll('tr'));
    var search = root.querySelector('[data-dataset-search]');
    var pageSize = root.querySelector('[data-dataset-page-size]');
    var count = root.querySelector('[data-dataset-count]');
    var page = root.querySelector('[data-dataset-page]');
    var prev = root.querySelector('[data-dataset-prev]');
    var next = root.querySelector('[data-dataset-next]');
    var sortButtons = Array.from(root.querySelectorAll('[data-dataset-sort]'));
    var state = { query: '', size: 10, page: 1, sortCol: null, sortDir: 1 };
    function filteredRows() {
      var query = normalize(state.query);
      var filtered = query === '' ? rows.slice() : rows.filter(function(row) {
        return normalize(row.textContent).indexOf(query) !== -1;
      });
      if (state.sortCol !== null) {
        filtered.sort(function(a, b) {
          var av = a.children[state.sortCol] ? a.children[state.sortCol].textContent.trim() : '';
          var bv = b.children[state.sortCol] ? b.children[state.sortCol].textContent.trim() : '';
          var an = numericValue(av);
          var bn = numericValue(bv);
          var result;
          if (an !== null && bn !== null) {
            result = an - bn;
          } else {
            result = normalize(av).localeCompare(normalize(bv), 'fr-CA', { numeric: true });
          }
          return result * state.sortDir;
        });
      }
      return filtered;
    }
    function render() {
      var filtered = filteredRows();
      var totalPages = Math.max(1, Math.ceil(filtered.length / state.size));
      state.page = Math.min(Math.max(1, state.page), totalPages);
      var start = (state.page - 1) * state.size;
      var visible = filtered.slice(start, start + state.size);
      filtered.forEach(function(row) { tbody.appendChild(row); });
      rows.filter(function(row) { return filtered.indexOf(row) === -1; }).forEach(function(row) { tbody.appendChild(row); });
      rows.forEach(function(row) { row.hidden = true; });
      visible.forEach(function(row) { row.hidden = false; });
      if (count) count.textContent = filtered.length + ' ligne' + (filtered.length > 1 ? 's' : '');
      if (page) page.textContent = 'Page ' + state.page + ' / ' + totalPages;
      if (prev) prev.disabled = state.page <= 1;
      if (next) next.disabled = state.page >= totalPages;
      sortButtons.forEach(function(button) {
        var indicator = button.querySelector('span');
        if (!indicator) return;
        var col = Number(button.dataset.datasetSort);
        indicator.textContent = col === state.sortCol ? (state.sortDir === 1 ? ' ↑' : ' ↓') : '';
      });
    }
    if (search) {
      search.addEventListener('input', function(event) {
        state.query = event.target.value;
        state.page = 1;
        render();
      });
    }
    if (pageSize) {
      state.size = Number(pageSize.value) || 10;
      pageSize.addEventListener('change', function(event) {
        state.size = Number(event.target.value) || 10;
        state.page = 1;
        render();
      });
    }
    if (prev) prev.addEventListener('click', function() { state.page -= 1; render(); });
    if (next) next.addEventListener('click', function() { state.page += 1; render(); });
    sortButtons.forEach(function(button) {
      button.addEventListener('click', function() {
        var col = Number(button.dataset.datasetSort);
        if (state.sortCol === col) {
          state.sortDir = state.sortDir * -1;
        } else {
          state.sortCol = col;
          state.sortDir = 1;
        }
        state.page = 1;
        render();
      });
    });
    render();
  }
  function initDocumentationPanel() {
    var panel = document.getElementById('documentation');
    if (!panel) return;
    function openForHash() {
      if (!window.location.hash) return;
      var id = window.location.hash.slice(1);
      if (id === 'documentation') {
        panel.open = true;
        return;
      }
      var target = document.getElementById(id);
      if (target && panel.contains(target)) panel.open = true;
    }
    window.addEventListener('hashchange', openForHash);
    openForHash();
  }
  function initAll() {
    initDocumentationPanel();
    document.querySelectorAll('.dataset-datatable').forEach(initDatatable);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initAll);
  } else {
    initAll();
  }
})();
</script>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button,
          { trigger: "manual",
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aureliennicosiaulaval\.github\.io\/donnees-bleues\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined;
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              }
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            }
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Données bleues</p>
</div>
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/AurelienNicosiaULaval/donnees-bleues/blob/main/datasets/etablissements-enseignement/fiche.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/AurelienNicosiaULaval/donnees-bleues/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Des données publiques à enseigner, avec contexte.</p>
</div>
  </div>
</footer>




</body></html>